// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package service_mocks

//go:generate minimock -i vilib-api/internal/service.GroupRole -o group_role_mock.go -n GroupRoleMock -p service_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"vilib-api/internal/domain"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// GroupRoleMock implements mm_service.GroupRole
type GroupRoleMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mGroupRoleMockCreate
}

// NewGroupRoleMock returns a mock for mm_service.GroupRole
func NewGroupRoleMock(t minimock.Tester) *GroupRoleMock {
	m := &GroupRoleMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mGroupRoleMockCreate{mock: m}
	m.CreateMock.callArgs = []*GroupRoleMockCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGroupRoleMockCreate struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockCreateExpectation
	expectations       []*GroupRoleMockCreateExpectation

	callArgs []*GroupRoleMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockCreateExpectation specifies expectation struct of the GroupRole.Create
type GroupRoleMockCreateExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockCreateParams
	paramPtrs          *GroupRoleMockCreateParamPtrs
	expectationOrigins GroupRoleMockCreateExpectationOrigins
	results            *GroupRoleMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockCreateParams contains parameters of the GroupRole.Create
type GroupRoleMockCreateParams struct {
	ctx       context.Context
	accountID uuid.UUID
	name      string
	mask      domain.PermissionMask
	isDefault bool
}

// GroupRoleMockCreateParamPtrs contains pointers to parameters of the GroupRole.Create
type GroupRoleMockCreateParamPtrs struct {
	ctx       *context.Context
	accountID *uuid.UUID
	name      *string
	mask      *domain.PermissionMask
	isDefault *bool
}

// GroupRoleMockCreateResults contains results of the GroupRole.Create
type GroupRoleMockCreateResults struct {
	g1  domain.GroupRole
	err error
}

// GroupRoleMockCreateOrigins contains origins of expectations of the GroupRole.Create
type GroupRoleMockCreateExpectationOrigins struct {
	origin          string
	originCtx       string
	originAccountID string
	originName      string
	originMask      string
	originIsDefault string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mGroupRoleMockCreate) Optional() *mGroupRoleMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Expect(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &GroupRoleMockCreateParams{ctx, accountID, name, mask, isDefault}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectAccountIDParam2 sets up expected param accountID for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectAccountIDParam2(accountID uuid.UUID) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.accountID = &accountID
	mmCreate.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectNameParam3 sets up expected param name for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectNameParam3(name string) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.name = &name
	mmCreate.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectMaskParam4 sets up expected param mask for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectMaskParam4(mask domain.PermissionMask) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.mask = &mask
	mmCreate.defaultExpectation.expectationOrigins.originMask = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectIsDefaultParam5 sets up expected param isDefault for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectIsDefaultParam5(isDefault bool) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.isDefault = &isDefault
	mmCreate.defaultExpectation.expectationOrigins.originIsDefault = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Inspect(f func(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool)) *mGroupRoleMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Return(g1 domain.GroupRole, err error) *GroupRoleMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &GroupRoleMockCreateResults{g1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the GroupRole.Create method
func (mmCreate *mGroupRoleMockCreate) Set(f func(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error)) *GroupRoleMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the GroupRole.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the GroupRole.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the GroupRole.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mGroupRoleMockCreate) When(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) *GroupRoleMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	expectation := &GroupRoleMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &GroupRoleMockCreateParams{ctx, accountID, name, mask, isDefault},
		expectationOrigins: GroupRoleMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.Create return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockCreateExpectation) Then(g1 domain.GroupRole, err error) *GroupRoleMock {
	e.results = &GroupRoleMockCreateResults{g1, err}
	return e.mock
}

// Times sets number of times GroupRole.Create should be invoked
func (mmCreate *mGroupRoleMockCreate) Times(n uint64) *mGroupRoleMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of GroupRoleMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mGroupRoleMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_service.GroupRole
func (mmCreate *GroupRoleMock) Create(ctx context.Context, accountID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, accountID, name, mask, isDefault)
	}

	mm_params := GroupRoleMockCreateParams{ctx, accountID, name, mask, isDefault}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.g1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockCreateParams{ctx, accountID, name, mask, isDefault}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

			if mm_want_ptrs.mask != nil && !minimock.Equal(*mm_want_ptrs.mask, mm_got.mask) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter mask, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originMask, *mm_want_ptrs.mask, mm_got.mask, minimock.Diff(*mm_want_ptrs.mask, mm_got.mask))
			}

			if mm_want_ptrs.isDefault != nil && !minimock.Equal(*mm_want_ptrs.isDefault, mm_got.isDefault) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter isDefault, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originIsDefault, *mm_want_ptrs.isDefault, mm_got.isDefault, minimock.Diff(*mm_want_ptrs.isDefault, mm_got.isDefault))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the GroupRoleMock.Create")
		}
		return (*mm_results).g1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, accountID, name, mask, isDefault)
	}
	mmCreate.t.Fatalf("Unexpected call to GroupRoleMock.Create. %v %v %v %v %v", ctx, accountID, name, mask, isDefault)
	return
}

// CreateAfterCounter returns a count of finished GroupRoleMock.Create invocations
func (mmCreate *GroupRoleMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of GroupRoleMock.Create invocations
func (mmCreate *GroupRoleMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mGroupRoleMockCreate) Calls() []*GroupRoleMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*GroupRoleMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GroupRoleMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GroupRoleMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GroupRoleMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
