// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package service_mocks

//go:generate minimock -i vilib-api/internal/service.GroupRole -o group_role_mock.go -n GroupRoleMock -p service_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"vilib-api/internal/domain"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// GroupRoleMock implements mm_service.GroupRole
type GroupRoleMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error)
	funcCreateOrigin    string
	inspectFuncCreate   func(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mGroupRoleMockCreate

	funcDelete          func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mGroupRoleMockDelete

	funcGetAll          func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID) (ga1 []domain.GroupRole, err error)
	funcGetAllOrigin    string
	inspectFuncGetAll   func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID)
	afterGetAllCounter  uint64
	beforeGetAllCounter uint64
	GetAllMock          mGroupRoleMockGetAll

	funcGetByID          func(ctx context.Context, roleID uuid.UUID) (ga1 []domain.GroupRole, err error)
	funcGetByIDOrigin    string
	inspectFuncGetByID   func(ctx context.Context, roleID uuid.UUID)
	afterGetByIDCounter  uint64
	beforeGetByIDCounter uint64
	GetByIDMock          mGroupRoleMockGetByID

	funcGetDefault          func(ctx context.Context, accountID uuid.UUID) (g1 domain.GroupRole, err error)
	funcGetDefaultOrigin    string
	inspectFuncGetDefault   func(ctx context.Context, accountID uuid.UUID)
	afterGetDefaultCounter  uint64
	beforeGetDefaultCounter uint64
	GetDefaultMock          mGroupRoleMockGetDefault
}

// NewGroupRoleMock returns a mock for mm_service.GroupRole
func NewGroupRoleMock(t minimock.Tester) *GroupRoleMock {
	m := &GroupRoleMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mGroupRoleMockCreate{mock: m}
	m.CreateMock.callArgs = []*GroupRoleMockCreateParams{}

	m.DeleteMock = mGroupRoleMockDelete{mock: m}
	m.DeleteMock.callArgs = []*GroupRoleMockDeleteParams{}

	m.GetAllMock = mGroupRoleMockGetAll{mock: m}
	m.GetAllMock.callArgs = []*GroupRoleMockGetAllParams{}

	m.GetByIDMock = mGroupRoleMockGetByID{mock: m}
	m.GetByIDMock.callArgs = []*GroupRoleMockGetByIDParams{}

	m.GetDefaultMock = mGroupRoleMockGetDefault{mock: m}
	m.GetDefaultMock.callArgs = []*GroupRoleMockGetDefaultParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGroupRoleMockCreate struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockCreateExpectation
	expectations       []*GroupRoleMockCreateExpectation

	callArgs []*GroupRoleMockCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockCreateExpectation specifies expectation struct of the GroupRole.Create
type GroupRoleMockCreateExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockCreateParams
	paramPtrs          *GroupRoleMockCreateParamPtrs
	expectationOrigins GroupRoleMockCreateExpectationOrigins
	results            *GroupRoleMockCreateResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockCreateParams contains parameters of the GroupRole.Create
type GroupRoleMockCreateParams struct {
	ctx         context.Context
	accountID   uuid.UUID
	initiatorID uuid.UUID
	name        string
	mask        domain.PermissionMask
	isDefault   bool
}

// GroupRoleMockCreateParamPtrs contains pointers to parameters of the GroupRole.Create
type GroupRoleMockCreateParamPtrs struct {
	ctx         *context.Context
	accountID   *uuid.UUID
	initiatorID *uuid.UUID
	name        *string
	mask        *domain.PermissionMask
	isDefault   *bool
}

// GroupRoleMockCreateResults contains results of the GroupRole.Create
type GroupRoleMockCreateResults struct {
	g1  domain.GroupRole
	err error
}

// GroupRoleMockCreateOrigins contains origins of expectations of the GroupRole.Create
type GroupRoleMockCreateExpectationOrigins struct {
	origin            string
	originCtx         string
	originAccountID   string
	originInitiatorID string
	originName        string
	originMask        string
	originIsDefault   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreate *mGroupRoleMockCreate) Optional() *mGroupRoleMockCreate {
	mmCreate.optional = true
	return mmCreate
}

// Expect sets up expected params for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Expect(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.paramPtrs != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by ExpectParams functions")
	}

	mmCreate.defaultExpectation.params = &GroupRoleMockCreateParams{ctx, accountID, initiatorID, name, mask, isDefault}
	mmCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectAccountIDParam2 sets up expected param accountID for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectAccountIDParam2(accountID uuid.UUID) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.accountID = &accountID
	mmCreate.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectInitiatorIDParam3 sets up expected param initiatorID for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectInitiatorIDParam3(initiatorID uuid.UUID) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.initiatorID = &initiatorID
	mmCreate.defaultExpectation.expectationOrigins.originInitiatorID = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectNameParam4 sets up expected param name for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectNameParam4(name string) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.name = &name
	mmCreate.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectMaskParam5 sets up expected param mask for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectMaskParam5(mask domain.PermissionMask) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.mask = &mask
	mmCreate.defaultExpectation.expectationOrigins.originMask = minimock.CallerInfo(1)

	return mmCreate
}

// ExpectIsDefaultParam6 sets up expected param isDefault for GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) ExpectIsDefaultParam6(isDefault bool) *mGroupRoleMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{}
	}

	if mmCreate.defaultExpectation.params != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Expect")
	}

	if mmCreate.defaultExpectation.paramPtrs == nil {
		mmCreate.defaultExpectation.paramPtrs = &GroupRoleMockCreateParamPtrs{}
	}
	mmCreate.defaultExpectation.paramPtrs.isDefault = &isDefault
	mmCreate.defaultExpectation.expectationOrigins.originIsDefault = minimock.CallerInfo(1)

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Inspect(f func(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool)) *mGroupRoleMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by GroupRole.Create
func (mmCreate *mGroupRoleMockCreate) Return(g1 domain.GroupRole, err error) *GroupRoleMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &GroupRoleMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &GroupRoleMockCreateResults{g1, err}
	mmCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// Set uses given function f to mock the GroupRole.Create method
func (mmCreate *mGroupRoleMockCreate) Set(f func(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error)) *GroupRoleMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the GroupRole.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the GroupRole.Create method")
	}

	mmCreate.mock.funcCreate = f
	mmCreate.mock.funcCreateOrigin = minimock.CallerInfo(1)
	return mmCreate.mock
}

// When sets expectation for the GroupRole.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mGroupRoleMockCreate) When(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) *GroupRoleMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("GroupRoleMock.Create mock is already set by Set")
	}

	expectation := &GroupRoleMockCreateExpectation{
		mock:               mmCreate.mock,
		params:             &GroupRoleMockCreateParams{ctx, accountID, initiatorID, name, mask, isDefault},
		expectationOrigins: GroupRoleMockCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.Create return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockCreateExpectation) Then(g1 domain.GroupRole, err error) *GroupRoleMock {
	e.results = &GroupRoleMockCreateResults{g1, err}
	return e.mock
}

// Times sets number of times GroupRole.Create should be invoked
func (mmCreate *mGroupRoleMockCreate) Times(n uint64) *mGroupRoleMockCreate {
	if n == 0 {
		mmCreate.mock.t.Fatalf("Times of GroupRoleMock.Create mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreate.expectedInvocations, n)
	mmCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreate
}

func (mmCreate *mGroupRoleMockCreate) invocationsDone() bool {
	if len(mmCreate.expectations) == 0 && mmCreate.defaultExpectation == nil && mmCreate.mock.funcCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreate.mock.afterCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Create implements mm_service.GroupRole
func (mmCreate *GroupRoleMock) Create(ctx context.Context, accountID uuid.UUID, initiatorID uuid.UUID, name string, mask domain.PermissionMask, isDefault bool) (g1 domain.GroupRole, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	mmCreate.t.Helper()

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, accountID, initiatorID, name, mask, isDefault)
	}

	mm_params := GroupRoleMockCreateParams{ctx, accountID, initiatorID, name, mask, isDefault}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.g1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_want_ptrs := mmCreate.CreateMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockCreateParams{ctx, accountID, initiatorID, name, mask, isDefault}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

			if mm_want_ptrs.initiatorID != nil && !minimock.Equal(*mm_want_ptrs.initiatorID, mm_got.initiatorID) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter initiatorID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originInitiatorID, *mm_want_ptrs.initiatorID, mm_got.initiatorID, minimock.Diff(*mm_want_ptrs.initiatorID, mm_got.initiatorID))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

			if mm_want_ptrs.mask != nil && !minimock.Equal(*mm_want_ptrs.mask, mm_got.mask) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter mask, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originMask, *mm_want_ptrs.mask, mm_got.mask, minimock.Diff(*mm_want_ptrs.mask, mm_got.mask))
			}

			if mm_want_ptrs.isDefault != nil && !minimock.Equal(*mm_want_ptrs.isDefault, mm_got.isDefault) {
				mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameter isDefault, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreate.CreateMock.defaultExpectation.expectationOrigins.originIsDefault, *mm_want_ptrs.isDefault, mm_got.isDefault, minimock.Diff(*mm_want_ptrs.isDefault, mm_got.isDefault))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("GroupRoleMock.Create got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreate.CreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the GroupRoleMock.Create")
		}
		return (*mm_results).g1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, accountID, initiatorID, name, mask, isDefault)
	}
	mmCreate.t.Fatalf("Unexpected call to GroupRoleMock.Create. %v %v %v %v %v %v", ctx, accountID, initiatorID, name, mask, isDefault)
	return
}

// CreateAfterCounter returns a count of finished GroupRoleMock.Create invocations
func (mmCreate *GroupRoleMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of GroupRoleMock.Create invocations
func (mmCreate *GroupRoleMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mGroupRoleMockCreate) Calls() []*GroupRoleMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*GroupRoleMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockCreateDone() bool {
	if m.CreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMock.invocationsDone()
}

// MinimockCreateInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateCounter := mm_atomic.LoadUint64(&m.afterCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && afterCreateCounter < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s", m.CreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s with params: %#v", m.CreateMock.defaultExpectation.expectationOrigins.origin, *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && afterCreateCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.Create at\n%s", m.funcCreateOrigin)
	}

	if !m.CreateMock.invocationsDone() && afterCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.Create at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMock.expectedInvocations), m.CreateMock.expectedInvocationsOrigin, afterCreateCounter)
	}
}

type mGroupRoleMockDelete struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockDeleteExpectation
	expectations       []*GroupRoleMockDeleteExpectation

	callArgs []*GroupRoleMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockDeleteExpectation specifies expectation struct of the GroupRole.Delete
type GroupRoleMockDeleteExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockDeleteParams
	paramPtrs          *GroupRoleMockDeleteParamPtrs
	expectationOrigins GroupRoleMockDeleteExpectationOrigins
	results            *GroupRoleMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockDeleteParams contains parameters of the GroupRole.Delete
type GroupRoleMockDeleteParams struct {
	ctx         context.Context
	initiatorID uuid.UUID
	accountID   uuid.UUID
	roleID      uuid.UUID
}

// GroupRoleMockDeleteParamPtrs contains pointers to parameters of the GroupRole.Delete
type GroupRoleMockDeleteParamPtrs struct {
	ctx         *context.Context
	initiatorID *uuid.UUID
	accountID   *uuid.UUID
	roleID      *uuid.UUID
}

// GroupRoleMockDeleteResults contains results of the GroupRole.Delete
type GroupRoleMockDeleteResults struct {
	err error
}

// GroupRoleMockDeleteOrigins contains origins of expectations of the GroupRole.Delete
type GroupRoleMockDeleteExpectationOrigins struct {
	origin            string
	originCtx         string
	originInitiatorID string
	originAccountID   string
	originRoleID      string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mGroupRoleMockDelete) Optional() *mGroupRoleMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) Expect(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID) *mGroupRoleMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &GroupRoleMockDeleteParams{ctx, initiatorID, accountID, roleID}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupRoleMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectInitiatorIDParam2 sets up expected param initiatorID for GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) ExpectInitiatorIDParam2(initiatorID uuid.UUID) *mGroupRoleMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupRoleMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.initiatorID = &initiatorID
	mmDelete.defaultExpectation.expectationOrigins.originInitiatorID = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectAccountIDParam3 sets up expected param accountID for GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) ExpectAccountIDParam3(accountID uuid.UUID) *mGroupRoleMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupRoleMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.accountID = &accountID
	mmDelete.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectRoleIDParam4 sets up expected param roleID for GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) ExpectRoleIDParam4(roleID uuid.UUID) *mGroupRoleMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupRoleMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.roleID = &roleID
	mmDelete.defaultExpectation.expectationOrigins.originRoleID = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) Inspect(f func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID)) *mGroupRoleMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by GroupRole.Delete
func (mmDelete *mGroupRoleMockDelete) Return(err error) *GroupRoleMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupRoleMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &GroupRoleMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the GroupRole.Delete method
func (mmDelete *mGroupRoleMockDelete) Set(f func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID) (err error)) *GroupRoleMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the GroupRole.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the GroupRole.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the GroupRole.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mGroupRoleMockDelete) When(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID) *GroupRoleMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupRoleMock.Delete mock is already set by Set")
	}

	expectation := &GroupRoleMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &GroupRoleMockDeleteParams{ctx, initiatorID, accountID, roleID},
		expectationOrigins: GroupRoleMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.Delete return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockDeleteExpectation) Then(err error) *GroupRoleMock {
	e.results = &GroupRoleMockDeleteResults{err}
	return e.mock
}

// Times sets number of times GroupRole.Delete should be invoked
func (mmDelete *mGroupRoleMockDelete) Times(n uint64) *mGroupRoleMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of GroupRoleMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mGroupRoleMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_service.GroupRole
func (mmDelete *GroupRoleMock) Delete(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID, roleID uuid.UUID) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, initiatorID, accountID, roleID)
	}

	mm_params := GroupRoleMockDeleteParams{ctx, initiatorID, accountID, roleID}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockDeleteParams{ctx, initiatorID, accountID, roleID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("GroupRoleMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.initiatorID != nil && !minimock.Equal(*mm_want_ptrs.initiatorID, mm_got.initiatorID) {
				mmDelete.t.Errorf("GroupRoleMock.Delete got unexpected parameter initiatorID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originInitiatorID, *mm_want_ptrs.initiatorID, mm_got.initiatorID, minimock.Diff(*mm_want_ptrs.initiatorID, mm_got.initiatorID))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmDelete.t.Errorf("GroupRoleMock.Delete got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

			if mm_want_ptrs.roleID != nil && !minimock.Equal(*mm_want_ptrs.roleID, mm_got.roleID) {
				mmDelete.t.Errorf("GroupRoleMock.Delete got unexpected parameter roleID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originRoleID, *mm_want_ptrs.roleID, mm_got.roleID, minimock.Diff(*mm_want_ptrs.roleID, mm_got.roleID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("GroupRoleMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the GroupRoleMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, initiatorID, accountID, roleID)
	}
	mmDelete.t.Fatalf("Unexpected call to GroupRoleMock.Delete. %v %v %v %v", ctx, initiatorID, accountID, roleID)
	return
}

// DeleteAfterCounter returns a count of finished GroupRoleMock.Delete invocations
func (mmDelete *GroupRoleMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of GroupRoleMock.Delete invocations
func (mmDelete *GroupRoleMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mGroupRoleMockDelete) Calls() []*GroupRoleMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*GroupRoleMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mGroupRoleMockGetAll struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockGetAllExpectation
	expectations       []*GroupRoleMockGetAllExpectation

	callArgs []*GroupRoleMockGetAllParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockGetAllExpectation specifies expectation struct of the GroupRole.GetAll
type GroupRoleMockGetAllExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockGetAllParams
	paramPtrs          *GroupRoleMockGetAllParamPtrs
	expectationOrigins GroupRoleMockGetAllExpectationOrigins
	results            *GroupRoleMockGetAllResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockGetAllParams contains parameters of the GroupRole.GetAll
type GroupRoleMockGetAllParams struct {
	ctx         context.Context
	initiatorID uuid.UUID
	accountID   uuid.UUID
}

// GroupRoleMockGetAllParamPtrs contains pointers to parameters of the GroupRole.GetAll
type GroupRoleMockGetAllParamPtrs struct {
	ctx         *context.Context
	initiatorID *uuid.UUID
	accountID   *uuid.UUID
}

// GroupRoleMockGetAllResults contains results of the GroupRole.GetAll
type GroupRoleMockGetAllResults struct {
	ga1 []domain.GroupRole
	err error
}

// GroupRoleMockGetAllOrigins contains origins of expectations of the GroupRole.GetAll
type GroupRoleMockGetAllExpectationOrigins struct {
	origin            string
	originCtx         string
	originInitiatorID string
	originAccountID   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetAll *mGroupRoleMockGetAll) Optional() *mGroupRoleMockGetAll {
	mmGetAll.optional = true
	return mmGetAll
}

// Expect sets up expected params for GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) Expect(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID) *mGroupRoleMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &GroupRoleMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.paramPtrs != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by ExpectParams functions")
	}

	mmGetAll.defaultExpectation.params = &GroupRoleMockGetAllParams{ctx, initiatorID, accountID}
	mmGetAll.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetAll.expectations {
		if minimock.Equal(e.params, mmGetAll.defaultExpectation.params) {
			mmGetAll.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetAll.defaultExpectation.params)
		}
	}

	return mmGetAll
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &GroupRoleMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.params != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Expect")
	}

	if mmGetAll.defaultExpectation.paramPtrs == nil {
		mmGetAll.defaultExpectation.paramPtrs = &GroupRoleMockGetAllParamPtrs{}
	}
	mmGetAll.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetAll.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetAll
}

// ExpectInitiatorIDParam2 sets up expected param initiatorID for GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) ExpectInitiatorIDParam2(initiatorID uuid.UUID) *mGroupRoleMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &GroupRoleMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.params != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Expect")
	}

	if mmGetAll.defaultExpectation.paramPtrs == nil {
		mmGetAll.defaultExpectation.paramPtrs = &GroupRoleMockGetAllParamPtrs{}
	}
	mmGetAll.defaultExpectation.paramPtrs.initiatorID = &initiatorID
	mmGetAll.defaultExpectation.expectationOrigins.originInitiatorID = minimock.CallerInfo(1)

	return mmGetAll
}

// ExpectAccountIDParam3 sets up expected param accountID for GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) ExpectAccountIDParam3(accountID uuid.UUID) *mGroupRoleMockGetAll {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &GroupRoleMockGetAllExpectation{}
	}

	if mmGetAll.defaultExpectation.params != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Expect")
	}

	if mmGetAll.defaultExpectation.paramPtrs == nil {
		mmGetAll.defaultExpectation.paramPtrs = &GroupRoleMockGetAllParamPtrs{}
	}
	mmGetAll.defaultExpectation.paramPtrs.accountID = &accountID
	mmGetAll.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmGetAll
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) Inspect(f func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID)) *mGroupRoleMockGetAll {
	if mmGetAll.mock.inspectFuncGetAll != nil {
		mmGetAll.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.GetAll")
	}

	mmGetAll.mock.inspectFuncGetAll = f

	return mmGetAll
}

// Return sets up results that will be returned by GroupRole.GetAll
func (mmGetAll *mGroupRoleMockGetAll) Return(ga1 []domain.GroupRole, err error) *GroupRoleMock {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	if mmGetAll.defaultExpectation == nil {
		mmGetAll.defaultExpectation = &GroupRoleMockGetAllExpectation{mock: mmGetAll.mock}
	}
	mmGetAll.defaultExpectation.results = &GroupRoleMockGetAllResults{ga1, err}
	mmGetAll.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// Set uses given function f to mock the GroupRole.GetAll method
func (mmGetAll *mGroupRoleMockGetAll) Set(f func(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID) (ga1 []domain.GroupRole, err error)) *GroupRoleMock {
	if mmGetAll.defaultExpectation != nil {
		mmGetAll.mock.t.Fatalf("Default expectation is already set for the GroupRole.GetAll method")
	}

	if len(mmGetAll.expectations) > 0 {
		mmGetAll.mock.t.Fatalf("Some expectations are already set for the GroupRole.GetAll method")
	}

	mmGetAll.mock.funcGetAll = f
	mmGetAll.mock.funcGetAllOrigin = minimock.CallerInfo(1)
	return mmGetAll.mock
}

// When sets expectation for the GroupRole.GetAll which will trigger the result defined by the following
// Then helper
func (mmGetAll *mGroupRoleMockGetAll) When(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID) *GroupRoleMockGetAllExpectation {
	if mmGetAll.mock.funcGetAll != nil {
		mmGetAll.mock.t.Fatalf("GroupRoleMock.GetAll mock is already set by Set")
	}

	expectation := &GroupRoleMockGetAllExpectation{
		mock:               mmGetAll.mock,
		params:             &GroupRoleMockGetAllParams{ctx, initiatorID, accountID},
		expectationOrigins: GroupRoleMockGetAllExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetAll.expectations = append(mmGetAll.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.GetAll return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockGetAllExpectation) Then(ga1 []domain.GroupRole, err error) *GroupRoleMock {
	e.results = &GroupRoleMockGetAllResults{ga1, err}
	return e.mock
}

// Times sets number of times GroupRole.GetAll should be invoked
func (mmGetAll *mGroupRoleMockGetAll) Times(n uint64) *mGroupRoleMockGetAll {
	if n == 0 {
		mmGetAll.mock.t.Fatalf("Times of GroupRoleMock.GetAll mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetAll.expectedInvocations, n)
	mmGetAll.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetAll
}

func (mmGetAll *mGroupRoleMockGetAll) invocationsDone() bool {
	if len(mmGetAll.expectations) == 0 && mmGetAll.defaultExpectation == nil && mmGetAll.mock.funcGetAll == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetAll.mock.afterGetAllCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetAll.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetAll implements mm_service.GroupRole
func (mmGetAll *GroupRoleMock) GetAll(ctx context.Context, initiatorID uuid.UUID, accountID uuid.UUID) (ga1 []domain.GroupRole, err error) {
	mm_atomic.AddUint64(&mmGetAll.beforeGetAllCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAll.afterGetAllCounter, 1)

	mmGetAll.t.Helper()

	if mmGetAll.inspectFuncGetAll != nil {
		mmGetAll.inspectFuncGetAll(ctx, initiatorID, accountID)
	}

	mm_params := GroupRoleMockGetAllParams{ctx, initiatorID, accountID}

	// Record call args
	mmGetAll.GetAllMock.mutex.Lock()
	mmGetAll.GetAllMock.callArgs = append(mmGetAll.GetAllMock.callArgs, &mm_params)
	mmGetAll.GetAllMock.mutex.Unlock()

	for _, e := range mmGetAll.GetAllMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ga1, e.results.err
		}
	}

	if mmGetAll.GetAllMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAll.GetAllMock.defaultExpectation.Counter, 1)
		mm_want := mmGetAll.GetAllMock.defaultExpectation.params
		mm_want_ptrs := mmGetAll.GetAllMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockGetAllParams{ctx, initiatorID, accountID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetAll.t.Errorf("GroupRoleMock.GetAll got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.initiatorID != nil && !minimock.Equal(*mm_want_ptrs.initiatorID, mm_got.initiatorID) {
				mmGetAll.t.Errorf("GroupRoleMock.GetAll got unexpected parameter initiatorID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.originInitiatorID, *mm_want_ptrs.initiatorID, mm_got.initiatorID, minimock.Diff(*mm_want_ptrs.initiatorID, mm_got.initiatorID))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmGetAll.t.Errorf("GroupRoleMock.GetAll got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetAll.t.Errorf("GroupRoleMock.GetAll got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetAll.GetAllMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetAll.GetAllMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAll.t.Fatal("No results are set for the GroupRoleMock.GetAll")
		}
		return (*mm_results).ga1, (*mm_results).err
	}
	if mmGetAll.funcGetAll != nil {
		return mmGetAll.funcGetAll(ctx, initiatorID, accountID)
	}
	mmGetAll.t.Fatalf("Unexpected call to GroupRoleMock.GetAll. %v %v %v", ctx, initiatorID, accountID)
	return
}

// GetAllAfterCounter returns a count of finished GroupRoleMock.GetAll invocations
func (mmGetAll *GroupRoleMock) GetAllAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.afterGetAllCounter)
}

// GetAllBeforeCounter returns a count of GroupRoleMock.GetAll invocations
func (mmGetAll *GroupRoleMock) GetAllBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAll.beforeGetAllCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.GetAll.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetAll *mGroupRoleMockGetAll) Calls() []*GroupRoleMockGetAllParams {
	mmGetAll.mutex.RLock()

	argCopy := make([]*GroupRoleMockGetAllParams, len(mmGetAll.callArgs))
	copy(argCopy, mmGetAll.callArgs)

	mmGetAll.mutex.RUnlock()

	return argCopy
}

// MinimockGetAllDone returns true if the count of the GetAll invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockGetAllDone() bool {
	if m.GetAllMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetAllMock.invocationsDone()
}

// MinimockGetAllInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockGetAllInspect() {
	for _, e := range m.GetAllMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.GetAll at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetAllCounter := mm_atomic.LoadUint64(&m.afterGetAllCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllMock.defaultExpectation != nil && afterGetAllCounter < 1 {
		if m.GetAllMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.GetAll at\n%s", m.GetAllMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.GetAll at\n%s with params: %#v", m.GetAllMock.defaultExpectation.expectationOrigins.origin, *m.GetAllMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAll != nil && afterGetAllCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.GetAll at\n%s", m.funcGetAllOrigin)
	}

	if !m.GetAllMock.invocationsDone() && afterGetAllCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.GetAll at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetAllMock.expectedInvocations), m.GetAllMock.expectedInvocationsOrigin, afterGetAllCounter)
	}
}

type mGroupRoleMockGetByID struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockGetByIDExpectation
	expectations       []*GroupRoleMockGetByIDExpectation

	callArgs []*GroupRoleMockGetByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockGetByIDExpectation specifies expectation struct of the GroupRole.GetByID
type GroupRoleMockGetByIDExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockGetByIDParams
	paramPtrs          *GroupRoleMockGetByIDParamPtrs
	expectationOrigins GroupRoleMockGetByIDExpectationOrigins
	results            *GroupRoleMockGetByIDResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockGetByIDParams contains parameters of the GroupRole.GetByID
type GroupRoleMockGetByIDParams struct {
	ctx    context.Context
	roleID uuid.UUID
}

// GroupRoleMockGetByIDParamPtrs contains pointers to parameters of the GroupRole.GetByID
type GroupRoleMockGetByIDParamPtrs struct {
	ctx    *context.Context
	roleID *uuid.UUID
}

// GroupRoleMockGetByIDResults contains results of the GroupRole.GetByID
type GroupRoleMockGetByIDResults struct {
	ga1 []domain.GroupRole
	err error
}

// GroupRoleMockGetByIDOrigins contains origins of expectations of the GroupRole.GetByID
type GroupRoleMockGetByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originRoleID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetByID *mGroupRoleMockGetByID) Optional() *mGroupRoleMockGetByID {
	mmGetByID.optional = true
	return mmGetByID
}

// Expect sets up expected params for GroupRole.GetByID
func (mmGetByID *mGroupRoleMockGetByID) Expect(ctx context.Context, roleID uuid.UUID) *mGroupRoleMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &GroupRoleMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.paramPtrs != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by ExpectParams functions")
	}

	mmGetByID.defaultExpectation.params = &GroupRoleMockGetByIDParams{ctx, roleID}
	mmGetByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetByID.expectations {
		if minimock.Equal(e.params, mmGetByID.defaultExpectation.params) {
			mmGetByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetByID.defaultExpectation.params)
		}
	}

	return mmGetByID
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.GetByID
func (mmGetByID *mGroupRoleMockGetByID) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &GroupRoleMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &GroupRoleMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetByID
}

// ExpectRoleIDParam2 sets up expected param roleID for GroupRole.GetByID
func (mmGetByID *mGroupRoleMockGetByID) ExpectRoleIDParam2(roleID uuid.UUID) *mGroupRoleMockGetByID {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &GroupRoleMockGetByIDExpectation{}
	}

	if mmGetByID.defaultExpectation.params != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Expect")
	}

	if mmGetByID.defaultExpectation.paramPtrs == nil {
		mmGetByID.defaultExpectation.paramPtrs = &GroupRoleMockGetByIDParamPtrs{}
	}
	mmGetByID.defaultExpectation.paramPtrs.roleID = &roleID
	mmGetByID.defaultExpectation.expectationOrigins.originRoleID = minimock.CallerInfo(1)

	return mmGetByID
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.GetByID
func (mmGetByID *mGroupRoleMockGetByID) Inspect(f func(ctx context.Context, roleID uuid.UUID)) *mGroupRoleMockGetByID {
	if mmGetByID.mock.inspectFuncGetByID != nil {
		mmGetByID.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.GetByID")
	}

	mmGetByID.mock.inspectFuncGetByID = f

	return mmGetByID
}

// Return sets up results that will be returned by GroupRole.GetByID
func (mmGetByID *mGroupRoleMockGetByID) Return(ga1 []domain.GroupRole, err error) *GroupRoleMock {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Set")
	}

	if mmGetByID.defaultExpectation == nil {
		mmGetByID.defaultExpectation = &GroupRoleMockGetByIDExpectation{mock: mmGetByID.mock}
	}
	mmGetByID.defaultExpectation.results = &GroupRoleMockGetByIDResults{ga1, err}
	mmGetByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// Set uses given function f to mock the GroupRole.GetByID method
func (mmGetByID *mGroupRoleMockGetByID) Set(f func(ctx context.Context, roleID uuid.UUID) (ga1 []domain.GroupRole, err error)) *GroupRoleMock {
	if mmGetByID.defaultExpectation != nil {
		mmGetByID.mock.t.Fatalf("Default expectation is already set for the GroupRole.GetByID method")
	}

	if len(mmGetByID.expectations) > 0 {
		mmGetByID.mock.t.Fatalf("Some expectations are already set for the GroupRole.GetByID method")
	}

	mmGetByID.mock.funcGetByID = f
	mmGetByID.mock.funcGetByIDOrigin = minimock.CallerInfo(1)
	return mmGetByID.mock
}

// When sets expectation for the GroupRole.GetByID which will trigger the result defined by the following
// Then helper
func (mmGetByID *mGroupRoleMockGetByID) When(ctx context.Context, roleID uuid.UUID) *GroupRoleMockGetByIDExpectation {
	if mmGetByID.mock.funcGetByID != nil {
		mmGetByID.mock.t.Fatalf("GroupRoleMock.GetByID mock is already set by Set")
	}

	expectation := &GroupRoleMockGetByIDExpectation{
		mock:               mmGetByID.mock,
		params:             &GroupRoleMockGetByIDParams{ctx, roleID},
		expectationOrigins: GroupRoleMockGetByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetByID.expectations = append(mmGetByID.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.GetByID return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockGetByIDExpectation) Then(ga1 []domain.GroupRole, err error) *GroupRoleMock {
	e.results = &GroupRoleMockGetByIDResults{ga1, err}
	return e.mock
}

// Times sets number of times GroupRole.GetByID should be invoked
func (mmGetByID *mGroupRoleMockGetByID) Times(n uint64) *mGroupRoleMockGetByID {
	if n == 0 {
		mmGetByID.mock.t.Fatalf("Times of GroupRoleMock.GetByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetByID.expectedInvocations, n)
	mmGetByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetByID
}

func (mmGetByID *mGroupRoleMockGetByID) invocationsDone() bool {
	if len(mmGetByID.expectations) == 0 && mmGetByID.defaultExpectation == nil && mmGetByID.mock.funcGetByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetByID.mock.afterGetByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetByID implements mm_service.GroupRole
func (mmGetByID *GroupRoleMock) GetByID(ctx context.Context, roleID uuid.UUID) (ga1 []domain.GroupRole, err error) {
	mm_atomic.AddUint64(&mmGetByID.beforeGetByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmGetByID.afterGetByIDCounter, 1)

	mmGetByID.t.Helper()

	if mmGetByID.inspectFuncGetByID != nil {
		mmGetByID.inspectFuncGetByID(ctx, roleID)
	}

	mm_params := GroupRoleMockGetByIDParams{ctx, roleID}

	// Record call args
	mmGetByID.GetByIDMock.mutex.Lock()
	mmGetByID.GetByIDMock.callArgs = append(mmGetByID.GetByIDMock.callArgs, &mm_params)
	mmGetByID.GetByIDMock.mutex.Unlock()

	for _, e := range mmGetByID.GetByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ga1, e.results.err
		}
	}

	if mmGetByID.GetByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetByID.GetByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmGetByID.GetByIDMock.defaultExpectation.params
		mm_want_ptrs := mmGetByID.GetByIDMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockGetByIDParams{ctx, roleID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetByID.t.Errorf("GroupRoleMock.GetByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.roleID != nil && !minimock.Equal(*mm_want_ptrs.roleID, mm_got.roleID) {
				mmGetByID.t.Errorf("GroupRoleMock.GetByID got unexpected parameter roleID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.originRoleID, *mm_want_ptrs.roleID, mm_got.roleID, minimock.Diff(*mm_want_ptrs.roleID, mm_got.roleID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetByID.t.Errorf("GroupRoleMock.GetByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetByID.GetByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetByID.GetByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmGetByID.t.Fatal("No results are set for the GroupRoleMock.GetByID")
		}
		return (*mm_results).ga1, (*mm_results).err
	}
	if mmGetByID.funcGetByID != nil {
		return mmGetByID.funcGetByID(ctx, roleID)
	}
	mmGetByID.t.Fatalf("Unexpected call to GroupRoleMock.GetByID. %v %v", ctx, roleID)
	return
}

// GetByIDAfterCounter returns a count of finished GroupRoleMock.GetByID invocations
func (mmGetByID *GroupRoleMock) GetByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.afterGetByIDCounter)
}

// GetByIDBeforeCounter returns a count of GroupRoleMock.GetByID invocations
func (mmGetByID *GroupRoleMock) GetByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetByID.beforeGetByIDCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.GetByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetByID *mGroupRoleMockGetByID) Calls() []*GroupRoleMockGetByIDParams {
	mmGetByID.mutex.RLock()

	argCopy := make([]*GroupRoleMockGetByIDParams, len(mmGetByID.callArgs))
	copy(argCopy, mmGetByID.callArgs)

	mmGetByID.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIDDone returns true if the count of the GetByID invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockGetByIDDone() bool {
	if m.GetByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIDMock.invocationsDone()
}

// MinimockGetByIDInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockGetByIDInspect() {
	for _, e := range m.GetByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.GetByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIDCounter := mm_atomic.LoadUint64(&m.afterGetByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIDMock.defaultExpectation != nil && afterGetByIDCounter < 1 {
		if m.GetByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.GetByID at\n%s", m.GetByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.GetByID at\n%s with params: %#v", m.GetByIDMock.defaultExpectation.expectationOrigins.origin, *m.GetByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetByID != nil && afterGetByIDCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.GetByID at\n%s", m.funcGetByIDOrigin)
	}

	if !m.GetByIDMock.invocationsDone() && afterGetByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.GetByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIDMock.expectedInvocations), m.GetByIDMock.expectedInvocationsOrigin, afterGetByIDCounter)
	}
}

type mGroupRoleMockGetDefault struct {
	optional           bool
	mock               *GroupRoleMock
	defaultExpectation *GroupRoleMockGetDefaultExpectation
	expectations       []*GroupRoleMockGetDefaultExpectation

	callArgs []*GroupRoleMockGetDefaultParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupRoleMockGetDefaultExpectation specifies expectation struct of the GroupRole.GetDefault
type GroupRoleMockGetDefaultExpectation struct {
	mock               *GroupRoleMock
	params             *GroupRoleMockGetDefaultParams
	paramPtrs          *GroupRoleMockGetDefaultParamPtrs
	expectationOrigins GroupRoleMockGetDefaultExpectationOrigins
	results            *GroupRoleMockGetDefaultResults
	returnOrigin       string
	Counter            uint64
}

// GroupRoleMockGetDefaultParams contains parameters of the GroupRole.GetDefault
type GroupRoleMockGetDefaultParams struct {
	ctx       context.Context
	accountID uuid.UUID
}

// GroupRoleMockGetDefaultParamPtrs contains pointers to parameters of the GroupRole.GetDefault
type GroupRoleMockGetDefaultParamPtrs struct {
	ctx       *context.Context
	accountID *uuid.UUID
}

// GroupRoleMockGetDefaultResults contains results of the GroupRole.GetDefault
type GroupRoleMockGetDefaultResults struct {
	g1  domain.GroupRole
	err error
}

// GroupRoleMockGetDefaultOrigins contains origins of expectations of the GroupRole.GetDefault
type GroupRoleMockGetDefaultExpectationOrigins struct {
	origin          string
	originCtx       string
	originAccountID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetDefault *mGroupRoleMockGetDefault) Optional() *mGroupRoleMockGetDefault {
	mmGetDefault.optional = true
	return mmGetDefault
}

// Expect sets up expected params for GroupRole.GetDefault
func (mmGetDefault *mGroupRoleMockGetDefault) Expect(ctx context.Context, accountID uuid.UUID) *mGroupRoleMockGetDefault {
	if mmGetDefault.mock.funcGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Set")
	}

	if mmGetDefault.defaultExpectation == nil {
		mmGetDefault.defaultExpectation = &GroupRoleMockGetDefaultExpectation{}
	}

	if mmGetDefault.defaultExpectation.paramPtrs != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by ExpectParams functions")
	}

	mmGetDefault.defaultExpectation.params = &GroupRoleMockGetDefaultParams{ctx, accountID}
	mmGetDefault.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetDefault.expectations {
		if minimock.Equal(e.params, mmGetDefault.defaultExpectation.params) {
			mmGetDefault.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetDefault.defaultExpectation.params)
		}
	}

	return mmGetDefault
}

// ExpectCtxParam1 sets up expected param ctx for GroupRole.GetDefault
func (mmGetDefault *mGroupRoleMockGetDefault) ExpectCtxParam1(ctx context.Context) *mGroupRoleMockGetDefault {
	if mmGetDefault.mock.funcGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Set")
	}

	if mmGetDefault.defaultExpectation == nil {
		mmGetDefault.defaultExpectation = &GroupRoleMockGetDefaultExpectation{}
	}

	if mmGetDefault.defaultExpectation.params != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Expect")
	}

	if mmGetDefault.defaultExpectation.paramPtrs == nil {
		mmGetDefault.defaultExpectation.paramPtrs = &GroupRoleMockGetDefaultParamPtrs{}
	}
	mmGetDefault.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetDefault.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetDefault
}

// ExpectAccountIDParam2 sets up expected param accountID for GroupRole.GetDefault
func (mmGetDefault *mGroupRoleMockGetDefault) ExpectAccountIDParam2(accountID uuid.UUID) *mGroupRoleMockGetDefault {
	if mmGetDefault.mock.funcGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Set")
	}

	if mmGetDefault.defaultExpectation == nil {
		mmGetDefault.defaultExpectation = &GroupRoleMockGetDefaultExpectation{}
	}

	if mmGetDefault.defaultExpectation.params != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Expect")
	}

	if mmGetDefault.defaultExpectation.paramPtrs == nil {
		mmGetDefault.defaultExpectation.paramPtrs = &GroupRoleMockGetDefaultParamPtrs{}
	}
	mmGetDefault.defaultExpectation.paramPtrs.accountID = &accountID
	mmGetDefault.defaultExpectation.expectationOrigins.originAccountID = minimock.CallerInfo(1)

	return mmGetDefault
}

// Inspect accepts an inspector function that has same arguments as the GroupRole.GetDefault
func (mmGetDefault *mGroupRoleMockGetDefault) Inspect(f func(ctx context.Context, accountID uuid.UUID)) *mGroupRoleMockGetDefault {
	if mmGetDefault.mock.inspectFuncGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("Inspect function is already set for GroupRoleMock.GetDefault")
	}

	mmGetDefault.mock.inspectFuncGetDefault = f

	return mmGetDefault
}

// Return sets up results that will be returned by GroupRole.GetDefault
func (mmGetDefault *mGroupRoleMockGetDefault) Return(g1 domain.GroupRole, err error) *GroupRoleMock {
	if mmGetDefault.mock.funcGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Set")
	}

	if mmGetDefault.defaultExpectation == nil {
		mmGetDefault.defaultExpectation = &GroupRoleMockGetDefaultExpectation{mock: mmGetDefault.mock}
	}
	mmGetDefault.defaultExpectation.results = &GroupRoleMockGetDefaultResults{g1, err}
	mmGetDefault.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetDefault.mock
}

// Set uses given function f to mock the GroupRole.GetDefault method
func (mmGetDefault *mGroupRoleMockGetDefault) Set(f func(ctx context.Context, accountID uuid.UUID) (g1 domain.GroupRole, err error)) *GroupRoleMock {
	if mmGetDefault.defaultExpectation != nil {
		mmGetDefault.mock.t.Fatalf("Default expectation is already set for the GroupRole.GetDefault method")
	}

	if len(mmGetDefault.expectations) > 0 {
		mmGetDefault.mock.t.Fatalf("Some expectations are already set for the GroupRole.GetDefault method")
	}

	mmGetDefault.mock.funcGetDefault = f
	mmGetDefault.mock.funcGetDefaultOrigin = minimock.CallerInfo(1)
	return mmGetDefault.mock
}

// When sets expectation for the GroupRole.GetDefault which will trigger the result defined by the following
// Then helper
func (mmGetDefault *mGroupRoleMockGetDefault) When(ctx context.Context, accountID uuid.UUID) *GroupRoleMockGetDefaultExpectation {
	if mmGetDefault.mock.funcGetDefault != nil {
		mmGetDefault.mock.t.Fatalf("GroupRoleMock.GetDefault mock is already set by Set")
	}

	expectation := &GroupRoleMockGetDefaultExpectation{
		mock:               mmGetDefault.mock,
		params:             &GroupRoleMockGetDefaultParams{ctx, accountID},
		expectationOrigins: GroupRoleMockGetDefaultExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetDefault.expectations = append(mmGetDefault.expectations, expectation)
	return expectation
}

// Then sets up GroupRole.GetDefault return parameters for the expectation previously defined by the When method
func (e *GroupRoleMockGetDefaultExpectation) Then(g1 domain.GroupRole, err error) *GroupRoleMock {
	e.results = &GroupRoleMockGetDefaultResults{g1, err}
	return e.mock
}

// Times sets number of times GroupRole.GetDefault should be invoked
func (mmGetDefault *mGroupRoleMockGetDefault) Times(n uint64) *mGroupRoleMockGetDefault {
	if n == 0 {
		mmGetDefault.mock.t.Fatalf("Times of GroupRoleMock.GetDefault mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetDefault.expectedInvocations, n)
	mmGetDefault.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetDefault
}

func (mmGetDefault *mGroupRoleMockGetDefault) invocationsDone() bool {
	if len(mmGetDefault.expectations) == 0 && mmGetDefault.defaultExpectation == nil && mmGetDefault.mock.funcGetDefault == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetDefault.mock.afterGetDefaultCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetDefault.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetDefault implements mm_service.GroupRole
func (mmGetDefault *GroupRoleMock) GetDefault(ctx context.Context, accountID uuid.UUID) (g1 domain.GroupRole, err error) {
	mm_atomic.AddUint64(&mmGetDefault.beforeGetDefaultCounter, 1)
	defer mm_atomic.AddUint64(&mmGetDefault.afterGetDefaultCounter, 1)

	mmGetDefault.t.Helper()

	if mmGetDefault.inspectFuncGetDefault != nil {
		mmGetDefault.inspectFuncGetDefault(ctx, accountID)
	}

	mm_params := GroupRoleMockGetDefaultParams{ctx, accountID}

	// Record call args
	mmGetDefault.GetDefaultMock.mutex.Lock()
	mmGetDefault.GetDefaultMock.callArgs = append(mmGetDefault.GetDefaultMock.callArgs, &mm_params)
	mmGetDefault.GetDefaultMock.mutex.Unlock()

	for _, e := range mmGetDefault.GetDefaultMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.g1, e.results.err
		}
	}

	if mmGetDefault.GetDefaultMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetDefault.GetDefaultMock.defaultExpectation.Counter, 1)
		mm_want := mmGetDefault.GetDefaultMock.defaultExpectation.params
		mm_want_ptrs := mmGetDefault.GetDefaultMock.defaultExpectation.paramPtrs

		mm_got := GroupRoleMockGetDefaultParams{ctx, accountID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetDefault.t.Errorf("GroupRoleMock.GetDefault got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetDefault.GetDefaultMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.accountID != nil && !minimock.Equal(*mm_want_ptrs.accountID, mm_got.accountID) {
				mmGetDefault.t.Errorf("GroupRoleMock.GetDefault got unexpected parameter accountID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetDefault.GetDefaultMock.defaultExpectation.expectationOrigins.originAccountID, *mm_want_ptrs.accountID, mm_got.accountID, minimock.Diff(*mm_want_ptrs.accountID, mm_got.accountID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetDefault.t.Errorf("GroupRoleMock.GetDefault got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetDefault.GetDefaultMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetDefault.GetDefaultMock.defaultExpectation.results
		if mm_results == nil {
			mmGetDefault.t.Fatal("No results are set for the GroupRoleMock.GetDefault")
		}
		return (*mm_results).g1, (*mm_results).err
	}
	if mmGetDefault.funcGetDefault != nil {
		return mmGetDefault.funcGetDefault(ctx, accountID)
	}
	mmGetDefault.t.Fatalf("Unexpected call to GroupRoleMock.GetDefault. %v %v", ctx, accountID)
	return
}

// GetDefaultAfterCounter returns a count of finished GroupRoleMock.GetDefault invocations
func (mmGetDefault *GroupRoleMock) GetDefaultAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetDefault.afterGetDefaultCounter)
}

// GetDefaultBeforeCounter returns a count of GroupRoleMock.GetDefault invocations
func (mmGetDefault *GroupRoleMock) GetDefaultBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetDefault.beforeGetDefaultCounter)
}

// Calls returns a list of arguments used in each call to GroupRoleMock.GetDefault.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetDefault *mGroupRoleMockGetDefault) Calls() []*GroupRoleMockGetDefaultParams {
	mmGetDefault.mutex.RLock()

	argCopy := make([]*GroupRoleMockGetDefaultParams, len(mmGetDefault.callArgs))
	copy(argCopy, mmGetDefault.callArgs)

	mmGetDefault.mutex.RUnlock()

	return argCopy
}

// MinimockGetDefaultDone returns true if the count of the GetDefault invocations corresponds
// the number of defined expectations
func (m *GroupRoleMock) MinimockGetDefaultDone() bool {
	if m.GetDefaultMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetDefaultMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetDefaultMock.invocationsDone()
}

// MinimockGetDefaultInspect logs each unmet expectation
func (m *GroupRoleMock) MinimockGetDefaultInspect() {
	for _, e := range m.GetDefaultMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupRoleMock.GetDefault at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetDefaultCounter := mm_atomic.LoadUint64(&m.afterGetDefaultCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetDefaultMock.defaultExpectation != nil && afterGetDefaultCounter < 1 {
		if m.GetDefaultMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupRoleMock.GetDefault at\n%s", m.GetDefaultMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupRoleMock.GetDefault at\n%s with params: %#v", m.GetDefaultMock.defaultExpectation.expectationOrigins.origin, *m.GetDefaultMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetDefault != nil && afterGetDefaultCounter < 1 {
		m.t.Errorf("Expected call to GroupRoleMock.GetDefault at\n%s", m.funcGetDefaultOrigin)
	}

	if !m.GetDefaultMock.invocationsDone() && afterGetDefaultCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupRoleMock.GetDefault at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetDefaultMock.expectedInvocations), m.GetDefaultMock.expectedInvocationsOrigin, afterGetDefaultCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GroupRoleMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()

			m.MinimockDeleteInspect()

			m.MinimockGetAllInspect()

			m.MinimockGetByIDInspect()

			m.MinimockGetDefaultInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GroupRoleMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GroupRoleMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone() &&
		m.MinimockDeleteDone() &&
		m.MinimockGetAllDone() &&
		m.MinimockGetByIDDone() &&
		m.MinimockGetDefaultDone()
}
