basePath: /api/v1
definitions:
  domain.PermissionMask:
    enum:
    - 0
    format: int64
    type: integer
    x-enum-varnames:
    - DefaultPermissionMask
  dto.AccountRole:
    properties:
      id:
        type: string
      is_default:
        type: boolean
      name:
        type: string
      parent_id:
        type: string
      permission:
        $ref: '#/definitions/domain.PermissionMask'
    type: object
  dto.AddGroupMemberRequest:
    properties:
      users:
        items:
          type: string
        type: array
    type: object
  dto.AddGroupMemberResponse:
    properties:
      members:
        items:
          $ref: '#/definitions/dto.GroupMember'
        type: array
    type: object
  dto.CreateAccountRoleRequest:
    properties:
      is_default:
        type: boolean
      name:
        type: string
      parent_id:
        type: string
      permission:
        $ref: '#/definitions/domain.PermissionMask'
    type: object
  dto.CreateAccountRoleResponse:
    properties:
      account_role:
        $ref: '#/definitions/dto.AccountRole'
    type: object
  dto.CreateGroupRoleRequest:
    properties:
      is_default:
        type: boolean
      name:
        type: string
      permission_mask:
        $ref: '#/definitions/domain.PermissionMask'
    type: object
  dto.CreateGroupRoleResponse:
    properties:
      role:
        $ref: '#/definitions/dto.GroupRole'
    type: object
  dto.CreateUserGroupRequest:
    properties:
      name:
        maxLength: 64
        type: string
      users:
        items:
          type: string
        type: array
    required:
    - name
    - users
    type: object
  dto.CreateUserGroupResponse:
    properties:
      id:
        type: string
      name:
        type: string
      users:
        items:
          $ref: '#/definitions/dto.GroupMember'
        type: array
    type: object
  dto.CreateUserRequest:
    properties:
      email:
        maxLength: 64
        type: string
      name:
        maxLength: 64
        minLength: 2
        type: string
      surname:
        maxLength: 64
        minLength: 2
        type: string
    required:
    - email
    - name
    - surname
    type: object
  dto.CreateUserResponse:
    properties:
      user:
        $ref: '#/definitions/dto.User'
    type: object
  dto.ErrorMessage:
    properties:
      message:
        type: string
    type: object
  dto.GetVideoResponse:
    properties:
      presigned_url:
        type: string
    type: object
  dto.GroupMember:
    properties:
      group_id:
        type: string
      role_id:
        type: string
      user_id:
        type: string
    type: object
  dto.GroupRole:
    properties:
      account_id:
        type: string
      id:
        type: string
      is_default:
        type: boolean
      name:
        type: string
      permission_mask:
        $ref: '#/definitions/domain.PermissionMask'
    type: object
  dto.LoginRequest:
    properties:
      email:
        maxLength: 64
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        maxLength: 64
        type: string
      name:
        maxLength: 64
        minLength: 2
        type: string
      surname:
        maxLength: 64
        minLength: 2
        type: string
    required:
    - email
    - name
    - surname
    type: object
  dto.RegisterResponse:
    type: object
  dto.UpdateUserRequest:
    properties:
      role_id:
        type: string
    type: object
  dto.UpdateUserResponse:
    properties:
      user:
        $ref: '#/definitions/dto.User'
    type: object
  dto.UploadVideoResponse:
    properties:
      presigned_url:
        type: string
    type: object
  dto.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role_id:
        type: string
      surname:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления внутренней видео документацией Vilib.
  title: Vilib API
  version: "1.0"
paths:
  /api/v1/accounts/{accountId}/roles:
    post:
      consumes:
      - application/json
      description: Создаёт новую роль для аккаунта с указанными правами
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: Тело запроса для создания роли
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateAccountRoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateAccountRoleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Создание роли аккаунта
      tags:
      - roles
  /api/v1/accounts/{accountId}/user-groups:
    post:
      consumes:
      - application/json
      description: Создаёт новую группу пользователей и добавляет указанных пользователей
        в неё
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: Тело запроса для создания группы
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserGroupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateUserGroupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Создание группы пользователей
      tags:
      - user-groups
  /api/v1/accounts/{accountId}/user-groups/{groupId}/members:
    post:
      consumes:
      - application/json
      description: Добавляет указанных пользователей в существующую группу
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: ID группы пользователей
        in: path
        name: groupId
        required: true
        type: string
      - description: Тело запроса для добавления участников
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AddGroupMemberRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AddGroupMemberResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Добавление участников в группу
      tags:
      - user-groups
  /api/v1/accounts/{accountId}/user-groups/{groupId}/video:
    post:
      consumes:
      - application/json
      description: Возвращает преподписанный URL для загрузки видео в S3
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: ID группы пользователей
        in: path
        name: groupId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UploadVideoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Загрузка видео
      tags:
      - video
  /api/v1/accounts/{accountId}/user-groups/{groupId}/video/{videoId}:
    get:
      consumes:
      - application/json
      description: Возвращает преподписанный URL для доступа к видео
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: ID группы пользователей
        in: path
        name: groupId
        required: true
        type: string
      - description: ID видео
        in: path
        name: videoId
        required: true
        type: string
      - description: Предпочитать оригинальное видео
        in: query
        name: prefer_original
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetVideoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Получение видео
      tags:
      - video
  /api/v1/accounts/{accountId}/user-groups/roles:
    post:
      consumes:
      - application/json
      description: Создаёт новую роль для группы пользователей с указанными правами
      parameters:
      - description: ID аккаунта
        in: path
        name: accountId
        required: true
        type: string
      - description: Тело запроса для создания роли группы
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateGroupRoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateGroupRoleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Создание роли группы
      tags:
      - roles
  /api/v1/accounts/{accountId}/users:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя с указанными данными, привязывает его
        к аккаунту и отправляет email с паролем
      parameters:
      - description: ID аккаунта, к которому привязывается пользователь
        in: path
        name: accountId
        required: true
        type: string
      - description: Тело запроса для создания пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Создание пользователя
      tags:
      - users
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя по email и паролю и возвращает токен
        авторизации
      parameters:
      - description: Тело запроса для входа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Вход пользователя
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Создаёт пользователя, аккаунт, назначает роль администратора и
        возвращает токен авторизации
      parameters:
      - description: Тело запроса для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Регистрация нового пользователя
      tags:
      - auth
  /api/v1/users/{user_id}:
    put:
      consumes:
      - application/json
      description: Обновляет данные пользователя (например, статус аккаунта)
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Тело запроса для обновления пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorMessage'
      summary: Обновление пользователя
      tags:
      - users
swagger: "2.0"
