// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package saga_mocks

//go:generate minimock -i vilib-api/internal/saga.Transactable -o transactable_mock.go -n TransactableMock -p saga_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/stephenafamo/bob"
)

// TransactableMock implements mm_saga.Transactable
type TransactableMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcWithTx          func(ctx context.Context) (t1 bob.Transaction, err error)
	funcWithTxOrigin    string
	inspectFuncWithTx   func(ctx context.Context)
	afterWithTxCounter  uint64
	beforeWithTxCounter uint64
	WithTxMock          mTransactableMockWithTx
}

// NewTransactableMock returns a mock for mm_saga.Transactable
func NewTransactableMock(t minimock.Tester) *TransactableMock {
	m := &TransactableMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.WithTxMock = mTransactableMockWithTx{mock: m}
	m.WithTxMock.callArgs = []*TransactableMockWithTxParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTransactableMockWithTx struct {
	optional           bool
	mock               *TransactableMock
	defaultExpectation *TransactableMockWithTxExpectation
	expectations       []*TransactableMockWithTxExpectation

	callArgs []*TransactableMockWithTxParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TransactableMockWithTxExpectation specifies expectation struct of the Transactable.WithTx
type TransactableMockWithTxExpectation struct {
	mock               *TransactableMock
	params             *TransactableMockWithTxParams
	paramPtrs          *TransactableMockWithTxParamPtrs
	expectationOrigins TransactableMockWithTxExpectationOrigins
	results            *TransactableMockWithTxResults
	returnOrigin       string
	Counter            uint64
}

// TransactableMockWithTxParams contains parameters of the Transactable.WithTx
type TransactableMockWithTxParams struct {
	ctx context.Context
}

// TransactableMockWithTxParamPtrs contains pointers to parameters of the Transactable.WithTx
type TransactableMockWithTxParamPtrs struct {
	ctx *context.Context
}

// TransactableMockWithTxResults contains results of the Transactable.WithTx
type TransactableMockWithTxResults struct {
	t1  bob.Transaction
	err error
}

// TransactableMockWithTxOrigins contains origins of expectations of the Transactable.WithTx
type TransactableMockWithTxExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmWithTx *mTransactableMockWithTx) Optional() *mTransactableMockWithTx {
	mmWithTx.optional = true
	return mmWithTx
}

// Expect sets up expected params for Transactable.WithTx
func (mmWithTx *mTransactableMockWithTx) Expect(ctx context.Context) *mTransactableMockWithTx {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &TransactableMockWithTxExpectation{}
	}

	if mmWithTx.defaultExpectation.paramPtrs != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by ExpectParams functions")
	}

	mmWithTx.defaultExpectation.params = &TransactableMockWithTxParams{ctx}
	mmWithTx.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmWithTx.expectations {
		if minimock.Equal(e.params, mmWithTx.defaultExpectation.params) {
			mmWithTx.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmWithTx.defaultExpectation.params)
		}
	}

	return mmWithTx
}

// ExpectCtxParam1 sets up expected param ctx for Transactable.WithTx
func (mmWithTx *mTransactableMockWithTx) ExpectCtxParam1(ctx context.Context) *mTransactableMockWithTx {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &TransactableMockWithTxExpectation{}
	}

	if mmWithTx.defaultExpectation.params != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by Expect")
	}

	if mmWithTx.defaultExpectation.paramPtrs == nil {
		mmWithTx.defaultExpectation.paramPtrs = &TransactableMockWithTxParamPtrs{}
	}
	mmWithTx.defaultExpectation.paramPtrs.ctx = &ctx
	mmWithTx.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmWithTx
}

// Inspect accepts an inspector function that has same arguments as the Transactable.WithTx
func (mmWithTx *mTransactableMockWithTx) Inspect(f func(ctx context.Context)) *mTransactableMockWithTx {
	if mmWithTx.mock.inspectFuncWithTx != nil {
		mmWithTx.mock.t.Fatalf("Inspect function is already set for TransactableMock.WithTx")
	}

	mmWithTx.mock.inspectFuncWithTx = f

	return mmWithTx
}

// Return sets up results that will be returned by Transactable.WithTx
func (mmWithTx *mTransactableMockWithTx) Return(t1 bob.Transaction, err error) *TransactableMock {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by Set")
	}

	if mmWithTx.defaultExpectation == nil {
		mmWithTx.defaultExpectation = &TransactableMockWithTxExpectation{mock: mmWithTx.mock}
	}
	mmWithTx.defaultExpectation.results = &TransactableMockWithTxResults{t1, err}
	mmWithTx.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmWithTx.mock
}

// Set uses given function f to mock the Transactable.WithTx method
func (mmWithTx *mTransactableMockWithTx) Set(f func(ctx context.Context) (t1 bob.Transaction, err error)) *TransactableMock {
	if mmWithTx.defaultExpectation != nil {
		mmWithTx.mock.t.Fatalf("Default expectation is already set for the Transactable.WithTx method")
	}

	if len(mmWithTx.expectations) > 0 {
		mmWithTx.mock.t.Fatalf("Some expectations are already set for the Transactable.WithTx method")
	}

	mmWithTx.mock.funcWithTx = f
	mmWithTx.mock.funcWithTxOrigin = minimock.CallerInfo(1)
	return mmWithTx.mock
}

// When sets expectation for the Transactable.WithTx which will trigger the result defined by the following
// Then helper
func (mmWithTx *mTransactableMockWithTx) When(ctx context.Context) *TransactableMockWithTxExpectation {
	if mmWithTx.mock.funcWithTx != nil {
		mmWithTx.mock.t.Fatalf("TransactableMock.WithTx mock is already set by Set")
	}

	expectation := &TransactableMockWithTxExpectation{
		mock:               mmWithTx.mock,
		params:             &TransactableMockWithTxParams{ctx},
		expectationOrigins: TransactableMockWithTxExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmWithTx.expectations = append(mmWithTx.expectations, expectation)
	return expectation
}

// Then sets up Transactable.WithTx return parameters for the expectation previously defined by the When method
func (e *TransactableMockWithTxExpectation) Then(t1 bob.Transaction, err error) *TransactableMock {
	e.results = &TransactableMockWithTxResults{t1, err}
	return e.mock
}

// Times sets number of times Transactable.WithTx should be invoked
func (mmWithTx *mTransactableMockWithTx) Times(n uint64) *mTransactableMockWithTx {
	if n == 0 {
		mmWithTx.mock.t.Fatalf("Times of TransactableMock.WithTx mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmWithTx.expectedInvocations, n)
	mmWithTx.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmWithTx
}

func (mmWithTx *mTransactableMockWithTx) invocationsDone() bool {
	if len(mmWithTx.expectations) == 0 && mmWithTx.defaultExpectation == nil && mmWithTx.mock.funcWithTx == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmWithTx.mock.afterWithTxCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmWithTx.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// WithTx implements mm_saga.Transactable
func (mmWithTx *TransactableMock) WithTx(ctx context.Context) (t1 bob.Transaction, err error) {
	mm_atomic.AddUint64(&mmWithTx.beforeWithTxCounter, 1)
	defer mm_atomic.AddUint64(&mmWithTx.afterWithTxCounter, 1)

	mmWithTx.t.Helper()

	if mmWithTx.inspectFuncWithTx != nil {
		mmWithTx.inspectFuncWithTx(ctx)
	}

	mm_params := TransactableMockWithTxParams{ctx}

	// Record call args
	mmWithTx.WithTxMock.mutex.Lock()
	mmWithTx.WithTxMock.callArgs = append(mmWithTx.WithTxMock.callArgs, &mm_params)
	mmWithTx.WithTxMock.mutex.Unlock()

	for _, e := range mmWithTx.WithTxMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.t1, e.results.err
		}
	}

	if mmWithTx.WithTxMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmWithTx.WithTxMock.defaultExpectation.Counter, 1)
		mm_want := mmWithTx.WithTxMock.defaultExpectation.params
		mm_want_ptrs := mmWithTx.WithTxMock.defaultExpectation.paramPtrs

		mm_got := TransactableMockWithTxParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmWithTx.t.Errorf("TransactableMock.WithTx got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmWithTx.WithTxMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmWithTx.t.Errorf("TransactableMock.WithTx got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmWithTx.WithTxMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmWithTx.WithTxMock.defaultExpectation.results
		if mm_results == nil {
			mmWithTx.t.Fatal("No results are set for the TransactableMock.WithTx")
		}
		return (*mm_results).t1, (*mm_results).err
	}
	if mmWithTx.funcWithTx != nil {
		return mmWithTx.funcWithTx(ctx)
	}
	mmWithTx.t.Fatalf("Unexpected call to TransactableMock.WithTx. %v", ctx)
	return
}

// WithTxAfterCounter returns a count of finished TransactableMock.WithTx invocations
func (mmWithTx *TransactableMock) WithTxAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithTx.afterWithTxCounter)
}

// WithTxBeforeCounter returns a count of TransactableMock.WithTx invocations
func (mmWithTx *TransactableMock) WithTxBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmWithTx.beforeWithTxCounter)
}

// Calls returns a list of arguments used in each call to TransactableMock.WithTx.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmWithTx *mTransactableMockWithTx) Calls() []*TransactableMockWithTxParams {
	mmWithTx.mutex.RLock()

	argCopy := make([]*TransactableMockWithTxParams, len(mmWithTx.callArgs))
	copy(argCopy, mmWithTx.callArgs)

	mmWithTx.mutex.RUnlock()

	return argCopy
}

// MinimockWithTxDone returns true if the count of the WithTx invocations corresponds
// the number of defined expectations
func (m *TransactableMock) MinimockWithTxDone() bool {
	if m.WithTxMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.WithTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.WithTxMock.invocationsDone()
}

// MinimockWithTxInspect logs each unmet expectation
func (m *TransactableMock) MinimockWithTxInspect() {
	for _, e := range m.WithTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TransactableMock.WithTx at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterWithTxCounter := mm_atomic.LoadUint64(&m.afterWithTxCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.WithTxMock.defaultExpectation != nil && afterWithTxCounter < 1 {
		if m.WithTxMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TransactableMock.WithTx at\n%s", m.WithTxMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TransactableMock.WithTx at\n%s with params: %#v", m.WithTxMock.defaultExpectation.expectationOrigins.origin, *m.WithTxMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcWithTx != nil && afterWithTxCounter < 1 {
		m.t.Errorf("Expected call to TransactableMock.WithTx at\n%s", m.funcWithTxOrigin)
	}

	if !m.WithTxMock.invocationsDone() && afterWithTxCounter > 0 {
		m.t.Errorf("Expected %d calls to TransactableMock.WithTx at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.WithTxMock.expectedInvocations), m.WithTxMock.expectedInvocationsOrigin, afterWithTxCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TransactableMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockWithTxInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TransactableMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TransactableMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockWithTxDone()
}
