// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package repository_mocks

//go:generate minimock -i vilib-api/internal/repository.AssignmentTarget -o assignment_target_mock.go -n AssignmentTargetMock -p repository_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"vilib-api/internal/domain"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// AssignmentTargetMock implements mm_repository.AssignmentTarget
type AssignmentTargetMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcInsertBatch          func(ctx context.Context, targets []domain.AssignmentTarget) (aa1 []domain.AssignmentTarget, err error)
	funcInsertBatchOrigin    string
	inspectFuncInsertBatch   func(ctx context.Context, targets []domain.AssignmentTarget)
	afterInsertBatchCounter  uint64
	beforeInsertBatchCounter uint64
	InsertBatchMock          mAssignmentTargetMockInsertBatch

	funcSelectByAssignmentIDs          func(ctx context.Context, assignmentIDs []uuid.UUID) (aa1 []domain.AssignmentTarget, err error)
	funcSelectByAssignmentIDsOrigin    string
	inspectFuncSelectByAssignmentIDs   func(ctx context.Context, assignmentIDs []uuid.UUID)
	afterSelectByAssignmentIDsCounter  uint64
	beforeSelectByAssignmentIDsCounter uint64
	SelectByAssignmentIDsMock          mAssignmentTargetMockSelectByAssignmentIDs
}

// NewAssignmentTargetMock returns a mock for mm_repository.AssignmentTarget
func NewAssignmentTargetMock(t minimock.Tester) *AssignmentTargetMock {
	m := &AssignmentTargetMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.InsertBatchMock = mAssignmentTargetMockInsertBatch{mock: m}
	m.InsertBatchMock.callArgs = []*AssignmentTargetMockInsertBatchParams{}

	m.SelectByAssignmentIDsMock = mAssignmentTargetMockSelectByAssignmentIDs{mock: m}
	m.SelectByAssignmentIDsMock.callArgs = []*AssignmentTargetMockSelectByAssignmentIDsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAssignmentTargetMockInsertBatch struct {
	optional           bool
	mock               *AssignmentTargetMock
	defaultExpectation *AssignmentTargetMockInsertBatchExpectation
	expectations       []*AssignmentTargetMockInsertBatchExpectation

	callArgs []*AssignmentTargetMockInsertBatchParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AssignmentTargetMockInsertBatchExpectation specifies expectation struct of the AssignmentTarget.InsertBatch
type AssignmentTargetMockInsertBatchExpectation struct {
	mock               *AssignmentTargetMock
	params             *AssignmentTargetMockInsertBatchParams
	paramPtrs          *AssignmentTargetMockInsertBatchParamPtrs
	expectationOrigins AssignmentTargetMockInsertBatchExpectationOrigins
	results            *AssignmentTargetMockInsertBatchResults
	returnOrigin       string
	Counter            uint64
}

// AssignmentTargetMockInsertBatchParams contains parameters of the AssignmentTarget.InsertBatch
type AssignmentTargetMockInsertBatchParams struct {
	ctx     context.Context
	targets []domain.AssignmentTarget
}

// AssignmentTargetMockInsertBatchParamPtrs contains pointers to parameters of the AssignmentTarget.InsertBatch
type AssignmentTargetMockInsertBatchParamPtrs struct {
	ctx     *context.Context
	targets *[]domain.AssignmentTarget
}

// AssignmentTargetMockInsertBatchResults contains results of the AssignmentTarget.InsertBatch
type AssignmentTargetMockInsertBatchResults struct {
	aa1 []domain.AssignmentTarget
	err error
}

// AssignmentTargetMockInsertBatchOrigins contains origins of expectations of the AssignmentTarget.InsertBatch
type AssignmentTargetMockInsertBatchExpectationOrigins struct {
	origin        string
	originCtx     string
	originTargets string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Optional() *mAssignmentTargetMockInsertBatch {
	mmInsertBatch.optional = true
	return mmInsertBatch
}

// Expect sets up expected params for AssignmentTarget.InsertBatch
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Expect(ctx context.Context, targets []domain.AssignmentTarget) *mAssignmentTargetMockInsertBatch {
	if mmInsertBatch.mock.funcInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Set")
	}

	if mmInsertBatch.defaultExpectation == nil {
		mmInsertBatch.defaultExpectation = &AssignmentTargetMockInsertBatchExpectation{}
	}

	if mmInsertBatch.defaultExpectation.paramPtrs != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by ExpectParams functions")
	}

	mmInsertBatch.defaultExpectation.params = &AssignmentTargetMockInsertBatchParams{ctx, targets}
	mmInsertBatch.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsertBatch.expectations {
		if minimock.Equal(e.params, mmInsertBatch.defaultExpectation.params) {
			mmInsertBatch.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsertBatch.defaultExpectation.params)
		}
	}

	return mmInsertBatch
}

// ExpectCtxParam1 sets up expected param ctx for AssignmentTarget.InsertBatch
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) ExpectCtxParam1(ctx context.Context) *mAssignmentTargetMockInsertBatch {
	if mmInsertBatch.mock.funcInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Set")
	}

	if mmInsertBatch.defaultExpectation == nil {
		mmInsertBatch.defaultExpectation = &AssignmentTargetMockInsertBatchExpectation{}
	}

	if mmInsertBatch.defaultExpectation.params != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Expect")
	}

	if mmInsertBatch.defaultExpectation.paramPtrs == nil {
		mmInsertBatch.defaultExpectation.paramPtrs = &AssignmentTargetMockInsertBatchParamPtrs{}
	}
	mmInsertBatch.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsertBatch.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsertBatch
}

// ExpectTargetsParam2 sets up expected param targets for AssignmentTarget.InsertBatch
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) ExpectTargetsParam2(targets []domain.AssignmentTarget) *mAssignmentTargetMockInsertBatch {
	if mmInsertBatch.mock.funcInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Set")
	}

	if mmInsertBatch.defaultExpectation == nil {
		mmInsertBatch.defaultExpectation = &AssignmentTargetMockInsertBatchExpectation{}
	}

	if mmInsertBatch.defaultExpectation.params != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Expect")
	}

	if mmInsertBatch.defaultExpectation.paramPtrs == nil {
		mmInsertBatch.defaultExpectation.paramPtrs = &AssignmentTargetMockInsertBatchParamPtrs{}
	}
	mmInsertBatch.defaultExpectation.paramPtrs.targets = &targets
	mmInsertBatch.defaultExpectation.expectationOrigins.originTargets = minimock.CallerInfo(1)

	return mmInsertBatch
}

// Inspect accepts an inspector function that has same arguments as the AssignmentTarget.InsertBatch
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Inspect(f func(ctx context.Context, targets []domain.AssignmentTarget)) *mAssignmentTargetMockInsertBatch {
	if mmInsertBatch.mock.inspectFuncInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("Inspect function is already set for AssignmentTargetMock.InsertBatch")
	}

	mmInsertBatch.mock.inspectFuncInsertBatch = f

	return mmInsertBatch
}

// Return sets up results that will be returned by AssignmentTarget.InsertBatch
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Return(aa1 []domain.AssignmentTarget, err error) *AssignmentTargetMock {
	if mmInsertBatch.mock.funcInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Set")
	}

	if mmInsertBatch.defaultExpectation == nil {
		mmInsertBatch.defaultExpectation = &AssignmentTargetMockInsertBatchExpectation{mock: mmInsertBatch.mock}
	}
	mmInsertBatch.defaultExpectation.results = &AssignmentTargetMockInsertBatchResults{aa1, err}
	mmInsertBatch.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsertBatch.mock
}

// Set uses given function f to mock the AssignmentTarget.InsertBatch method
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Set(f func(ctx context.Context, targets []domain.AssignmentTarget) (aa1 []domain.AssignmentTarget, err error)) *AssignmentTargetMock {
	if mmInsertBatch.defaultExpectation != nil {
		mmInsertBatch.mock.t.Fatalf("Default expectation is already set for the AssignmentTarget.InsertBatch method")
	}

	if len(mmInsertBatch.expectations) > 0 {
		mmInsertBatch.mock.t.Fatalf("Some expectations are already set for the AssignmentTarget.InsertBatch method")
	}

	mmInsertBatch.mock.funcInsertBatch = f
	mmInsertBatch.mock.funcInsertBatchOrigin = minimock.CallerInfo(1)
	return mmInsertBatch.mock
}

// When sets expectation for the AssignmentTarget.InsertBatch which will trigger the result defined by the following
// Then helper
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) When(ctx context.Context, targets []domain.AssignmentTarget) *AssignmentTargetMockInsertBatchExpectation {
	if mmInsertBatch.mock.funcInsertBatch != nil {
		mmInsertBatch.mock.t.Fatalf("AssignmentTargetMock.InsertBatch mock is already set by Set")
	}

	expectation := &AssignmentTargetMockInsertBatchExpectation{
		mock:               mmInsertBatch.mock,
		params:             &AssignmentTargetMockInsertBatchParams{ctx, targets},
		expectationOrigins: AssignmentTargetMockInsertBatchExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsertBatch.expectations = append(mmInsertBatch.expectations, expectation)
	return expectation
}

// Then sets up AssignmentTarget.InsertBatch return parameters for the expectation previously defined by the When method
func (e *AssignmentTargetMockInsertBatchExpectation) Then(aa1 []domain.AssignmentTarget, err error) *AssignmentTargetMock {
	e.results = &AssignmentTargetMockInsertBatchResults{aa1, err}
	return e.mock
}

// Times sets number of times AssignmentTarget.InsertBatch should be invoked
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Times(n uint64) *mAssignmentTargetMockInsertBatch {
	if n == 0 {
		mmInsertBatch.mock.t.Fatalf("Times of AssignmentTargetMock.InsertBatch mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsertBatch.expectedInvocations, n)
	mmInsertBatch.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsertBatch
}

func (mmInsertBatch *mAssignmentTargetMockInsertBatch) invocationsDone() bool {
	if len(mmInsertBatch.expectations) == 0 && mmInsertBatch.defaultExpectation == nil && mmInsertBatch.mock.funcInsertBatch == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsertBatch.mock.afterInsertBatchCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsertBatch.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InsertBatch implements mm_repository.AssignmentTarget
func (mmInsertBatch *AssignmentTargetMock) InsertBatch(ctx context.Context, targets []domain.AssignmentTarget) (aa1 []domain.AssignmentTarget, err error) {
	mm_atomic.AddUint64(&mmInsertBatch.beforeInsertBatchCounter, 1)
	defer mm_atomic.AddUint64(&mmInsertBatch.afterInsertBatchCounter, 1)

	mmInsertBatch.t.Helper()

	if mmInsertBatch.inspectFuncInsertBatch != nil {
		mmInsertBatch.inspectFuncInsertBatch(ctx, targets)
	}

	mm_params := AssignmentTargetMockInsertBatchParams{ctx, targets}

	// Record call args
	mmInsertBatch.InsertBatchMock.mutex.Lock()
	mmInsertBatch.InsertBatchMock.callArgs = append(mmInsertBatch.InsertBatchMock.callArgs, &mm_params)
	mmInsertBatch.InsertBatchMock.mutex.Unlock()

	for _, e := range mmInsertBatch.InsertBatchMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.aa1, e.results.err
		}
	}

	if mmInsertBatch.InsertBatchMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsertBatch.InsertBatchMock.defaultExpectation.Counter, 1)
		mm_want := mmInsertBatch.InsertBatchMock.defaultExpectation.params
		mm_want_ptrs := mmInsertBatch.InsertBatchMock.defaultExpectation.paramPtrs

		mm_got := AssignmentTargetMockInsertBatchParams{ctx, targets}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsertBatch.t.Errorf("AssignmentTargetMock.InsertBatch got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertBatch.InsertBatchMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.targets != nil && !minimock.Equal(*mm_want_ptrs.targets, mm_got.targets) {
				mmInsertBatch.t.Errorf("AssignmentTargetMock.InsertBatch got unexpected parameter targets, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsertBatch.InsertBatchMock.defaultExpectation.expectationOrigins.originTargets, *mm_want_ptrs.targets, mm_got.targets, minimock.Diff(*mm_want_ptrs.targets, mm_got.targets))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsertBatch.t.Errorf("AssignmentTargetMock.InsertBatch got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsertBatch.InsertBatchMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsertBatch.InsertBatchMock.defaultExpectation.results
		if mm_results == nil {
			mmInsertBatch.t.Fatal("No results are set for the AssignmentTargetMock.InsertBatch")
		}
		return (*mm_results).aa1, (*mm_results).err
	}
	if mmInsertBatch.funcInsertBatch != nil {
		return mmInsertBatch.funcInsertBatch(ctx, targets)
	}
	mmInsertBatch.t.Fatalf("Unexpected call to AssignmentTargetMock.InsertBatch. %v %v", ctx, targets)
	return
}

// InsertBatchAfterCounter returns a count of finished AssignmentTargetMock.InsertBatch invocations
func (mmInsertBatch *AssignmentTargetMock) InsertBatchAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertBatch.afterInsertBatchCounter)
}

// InsertBatchBeforeCounter returns a count of AssignmentTargetMock.InsertBatch invocations
func (mmInsertBatch *AssignmentTargetMock) InsertBatchBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsertBatch.beforeInsertBatchCounter)
}

// Calls returns a list of arguments used in each call to AssignmentTargetMock.InsertBatch.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsertBatch *mAssignmentTargetMockInsertBatch) Calls() []*AssignmentTargetMockInsertBatchParams {
	mmInsertBatch.mutex.RLock()

	argCopy := make([]*AssignmentTargetMockInsertBatchParams, len(mmInsertBatch.callArgs))
	copy(argCopy, mmInsertBatch.callArgs)

	mmInsertBatch.mutex.RUnlock()

	return argCopy
}

// MinimockInsertBatchDone returns true if the count of the InsertBatch invocations corresponds
// the number of defined expectations
func (m *AssignmentTargetMock) MinimockInsertBatchDone() bool {
	if m.InsertBatchMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertBatchMock.invocationsDone()
}

// MinimockInsertBatchInspect logs each unmet expectation
func (m *AssignmentTargetMock) MinimockInsertBatchInspect() {
	for _, e := range m.InsertBatchMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AssignmentTargetMock.InsertBatch at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertBatchCounter := mm_atomic.LoadUint64(&m.afterInsertBatchCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertBatchMock.defaultExpectation != nil && afterInsertBatchCounter < 1 {
		if m.InsertBatchMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AssignmentTargetMock.InsertBatch at\n%s", m.InsertBatchMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AssignmentTargetMock.InsertBatch at\n%s with params: %#v", m.InsertBatchMock.defaultExpectation.expectationOrigins.origin, *m.InsertBatchMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsertBatch != nil && afterInsertBatchCounter < 1 {
		m.t.Errorf("Expected call to AssignmentTargetMock.InsertBatch at\n%s", m.funcInsertBatchOrigin)
	}

	if !m.InsertBatchMock.invocationsDone() && afterInsertBatchCounter > 0 {
		m.t.Errorf("Expected %d calls to AssignmentTargetMock.InsertBatch at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertBatchMock.expectedInvocations), m.InsertBatchMock.expectedInvocationsOrigin, afterInsertBatchCounter)
	}
}

type mAssignmentTargetMockSelectByAssignmentIDs struct {
	optional           bool
	mock               *AssignmentTargetMock
	defaultExpectation *AssignmentTargetMockSelectByAssignmentIDsExpectation
	expectations       []*AssignmentTargetMockSelectByAssignmentIDsExpectation

	callArgs []*AssignmentTargetMockSelectByAssignmentIDsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AssignmentTargetMockSelectByAssignmentIDsExpectation specifies expectation struct of the AssignmentTarget.SelectByAssignmentIDs
type AssignmentTargetMockSelectByAssignmentIDsExpectation struct {
	mock               *AssignmentTargetMock
	params             *AssignmentTargetMockSelectByAssignmentIDsParams
	paramPtrs          *AssignmentTargetMockSelectByAssignmentIDsParamPtrs
	expectationOrigins AssignmentTargetMockSelectByAssignmentIDsExpectationOrigins
	results            *AssignmentTargetMockSelectByAssignmentIDsResults
	returnOrigin       string
	Counter            uint64
}

// AssignmentTargetMockSelectByAssignmentIDsParams contains parameters of the AssignmentTarget.SelectByAssignmentIDs
type AssignmentTargetMockSelectByAssignmentIDsParams struct {
	ctx           context.Context
	assignmentIDs []uuid.UUID
}

// AssignmentTargetMockSelectByAssignmentIDsParamPtrs contains pointers to parameters of the AssignmentTarget.SelectByAssignmentIDs
type AssignmentTargetMockSelectByAssignmentIDsParamPtrs struct {
	ctx           *context.Context
	assignmentIDs *[]uuid.UUID
}

// AssignmentTargetMockSelectByAssignmentIDsResults contains results of the AssignmentTarget.SelectByAssignmentIDs
type AssignmentTargetMockSelectByAssignmentIDsResults struct {
	aa1 []domain.AssignmentTarget
	err error
}

// AssignmentTargetMockSelectByAssignmentIDsOrigins contains origins of expectations of the AssignmentTarget.SelectByAssignmentIDs
type AssignmentTargetMockSelectByAssignmentIDsExpectationOrigins struct {
	origin              string
	originCtx           string
	originAssignmentIDs string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Optional() *mAssignmentTargetMockSelectByAssignmentIDs {
	mmSelectByAssignmentIDs.optional = true
	return mmSelectByAssignmentIDs
}

// Expect sets up expected params for AssignmentTarget.SelectByAssignmentIDs
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Expect(ctx context.Context, assignmentIDs []uuid.UUID) *mAssignmentTargetMockSelectByAssignmentIDs {
	if mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Set")
	}

	if mmSelectByAssignmentIDs.defaultExpectation == nil {
		mmSelectByAssignmentIDs.defaultExpectation = &AssignmentTargetMockSelectByAssignmentIDsExpectation{}
	}

	if mmSelectByAssignmentIDs.defaultExpectation.paramPtrs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by ExpectParams functions")
	}

	mmSelectByAssignmentIDs.defaultExpectation.params = &AssignmentTargetMockSelectByAssignmentIDsParams{ctx, assignmentIDs}
	mmSelectByAssignmentIDs.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectByAssignmentIDs.expectations {
		if minimock.Equal(e.params, mmSelectByAssignmentIDs.defaultExpectation.params) {
			mmSelectByAssignmentIDs.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectByAssignmentIDs.defaultExpectation.params)
		}
	}

	return mmSelectByAssignmentIDs
}

// ExpectCtxParam1 sets up expected param ctx for AssignmentTarget.SelectByAssignmentIDs
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) ExpectCtxParam1(ctx context.Context) *mAssignmentTargetMockSelectByAssignmentIDs {
	if mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Set")
	}

	if mmSelectByAssignmentIDs.defaultExpectation == nil {
		mmSelectByAssignmentIDs.defaultExpectation = &AssignmentTargetMockSelectByAssignmentIDsExpectation{}
	}

	if mmSelectByAssignmentIDs.defaultExpectation.params != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Expect")
	}

	if mmSelectByAssignmentIDs.defaultExpectation.paramPtrs == nil {
		mmSelectByAssignmentIDs.defaultExpectation.paramPtrs = &AssignmentTargetMockSelectByAssignmentIDsParamPtrs{}
	}
	mmSelectByAssignmentIDs.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectByAssignmentIDs.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectByAssignmentIDs
}

// ExpectAssignmentIDsParam2 sets up expected param assignmentIDs for AssignmentTarget.SelectByAssignmentIDs
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) ExpectAssignmentIDsParam2(assignmentIDs []uuid.UUID) *mAssignmentTargetMockSelectByAssignmentIDs {
	if mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Set")
	}

	if mmSelectByAssignmentIDs.defaultExpectation == nil {
		mmSelectByAssignmentIDs.defaultExpectation = &AssignmentTargetMockSelectByAssignmentIDsExpectation{}
	}

	if mmSelectByAssignmentIDs.defaultExpectation.params != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Expect")
	}

	if mmSelectByAssignmentIDs.defaultExpectation.paramPtrs == nil {
		mmSelectByAssignmentIDs.defaultExpectation.paramPtrs = &AssignmentTargetMockSelectByAssignmentIDsParamPtrs{}
	}
	mmSelectByAssignmentIDs.defaultExpectation.paramPtrs.assignmentIDs = &assignmentIDs
	mmSelectByAssignmentIDs.defaultExpectation.expectationOrigins.originAssignmentIDs = minimock.CallerInfo(1)

	return mmSelectByAssignmentIDs
}

// Inspect accepts an inspector function that has same arguments as the AssignmentTarget.SelectByAssignmentIDs
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Inspect(f func(ctx context.Context, assignmentIDs []uuid.UUID)) *mAssignmentTargetMockSelectByAssignmentIDs {
	if mmSelectByAssignmentIDs.mock.inspectFuncSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("Inspect function is already set for AssignmentTargetMock.SelectByAssignmentIDs")
	}

	mmSelectByAssignmentIDs.mock.inspectFuncSelectByAssignmentIDs = f

	return mmSelectByAssignmentIDs
}

// Return sets up results that will be returned by AssignmentTarget.SelectByAssignmentIDs
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Return(aa1 []domain.AssignmentTarget, err error) *AssignmentTargetMock {
	if mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Set")
	}

	if mmSelectByAssignmentIDs.defaultExpectation == nil {
		mmSelectByAssignmentIDs.defaultExpectation = &AssignmentTargetMockSelectByAssignmentIDsExpectation{mock: mmSelectByAssignmentIDs.mock}
	}
	mmSelectByAssignmentIDs.defaultExpectation.results = &AssignmentTargetMockSelectByAssignmentIDsResults{aa1, err}
	mmSelectByAssignmentIDs.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectByAssignmentIDs.mock
}

// Set uses given function f to mock the AssignmentTarget.SelectByAssignmentIDs method
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Set(f func(ctx context.Context, assignmentIDs []uuid.UUID) (aa1 []domain.AssignmentTarget, err error)) *AssignmentTargetMock {
	if mmSelectByAssignmentIDs.defaultExpectation != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("Default expectation is already set for the AssignmentTarget.SelectByAssignmentIDs method")
	}

	if len(mmSelectByAssignmentIDs.expectations) > 0 {
		mmSelectByAssignmentIDs.mock.t.Fatalf("Some expectations are already set for the AssignmentTarget.SelectByAssignmentIDs method")
	}

	mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs = f
	mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDsOrigin = minimock.CallerInfo(1)
	return mmSelectByAssignmentIDs.mock
}

// When sets expectation for the AssignmentTarget.SelectByAssignmentIDs which will trigger the result defined by the following
// Then helper
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) When(ctx context.Context, assignmentIDs []uuid.UUID) *AssignmentTargetMockSelectByAssignmentIDsExpectation {
	if mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.mock.t.Fatalf("AssignmentTargetMock.SelectByAssignmentIDs mock is already set by Set")
	}

	expectation := &AssignmentTargetMockSelectByAssignmentIDsExpectation{
		mock:               mmSelectByAssignmentIDs.mock,
		params:             &AssignmentTargetMockSelectByAssignmentIDsParams{ctx, assignmentIDs},
		expectationOrigins: AssignmentTargetMockSelectByAssignmentIDsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectByAssignmentIDs.expectations = append(mmSelectByAssignmentIDs.expectations, expectation)
	return expectation
}

// Then sets up AssignmentTarget.SelectByAssignmentIDs return parameters for the expectation previously defined by the When method
func (e *AssignmentTargetMockSelectByAssignmentIDsExpectation) Then(aa1 []domain.AssignmentTarget, err error) *AssignmentTargetMock {
	e.results = &AssignmentTargetMockSelectByAssignmentIDsResults{aa1, err}
	return e.mock
}

// Times sets number of times AssignmentTarget.SelectByAssignmentIDs should be invoked
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Times(n uint64) *mAssignmentTargetMockSelectByAssignmentIDs {
	if n == 0 {
		mmSelectByAssignmentIDs.mock.t.Fatalf("Times of AssignmentTargetMock.SelectByAssignmentIDs mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectByAssignmentIDs.expectedInvocations, n)
	mmSelectByAssignmentIDs.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectByAssignmentIDs
}

func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) invocationsDone() bool {
	if len(mmSelectByAssignmentIDs.expectations) == 0 && mmSelectByAssignmentIDs.defaultExpectation == nil && mmSelectByAssignmentIDs.mock.funcSelectByAssignmentIDs == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectByAssignmentIDs.mock.afterSelectByAssignmentIDsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectByAssignmentIDs.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectByAssignmentIDs implements mm_repository.AssignmentTarget
func (mmSelectByAssignmentIDs *AssignmentTargetMock) SelectByAssignmentIDs(ctx context.Context, assignmentIDs []uuid.UUID) (aa1 []domain.AssignmentTarget, err error) {
	mm_atomic.AddUint64(&mmSelectByAssignmentIDs.beforeSelectByAssignmentIDsCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectByAssignmentIDs.afterSelectByAssignmentIDsCounter, 1)

	mmSelectByAssignmentIDs.t.Helper()

	if mmSelectByAssignmentIDs.inspectFuncSelectByAssignmentIDs != nil {
		mmSelectByAssignmentIDs.inspectFuncSelectByAssignmentIDs(ctx, assignmentIDs)
	}

	mm_params := AssignmentTargetMockSelectByAssignmentIDsParams{ctx, assignmentIDs}

	// Record call args
	mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.mutex.Lock()
	mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.callArgs = append(mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.callArgs, &mm_params)
	mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.mutex.Unlock()

	for _, e := range mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.aa1, e.results.err
		}
	}

	if mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.params
		mm_want_ptrs := mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.paramPtrs

		mm_got := AssignmentTargetMockSelectByAssignmentIDsParams{ctx, assignmentIDs}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectByAssignmentIDs.t.Errorf("AssignmentTargetMock.SelectByAssignmentIDs got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.assignmentIDs != nil && !minimock.Equal(*mm_want_ptrs.assignmentIDs, mm_got.assignmentIDs) {
				mmSelectByAssignmentIDs.t.Errorf("AssignmentTargetMock.SelectByAssignmentIDs got unexpected parameter assignmentIDs, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.expectationOrigins.originAssignmentIDs, *mm_want_ptrs.assignmentIDs, mm_got.assignmentIDs, minimock.Diff(*mm_want_ptrs.assignmentIDs, mm_got.assignmentIDs))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectByAssignmentIDs.t.Errorf("AssignmentTargetMock.SelectByAssignmentIDs got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectByAssignmentIDs.SelectByAssignmentIDsMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectByAssignmentIDs.t.Fatal("No results are set for the AssignmentTargetMock.SelectByAssignmentIDs")
		}
		return (*mm_results).aa1, (*mm_results).err
	}
	if mmSelectByAssignmentIDs.funcSelectByAssignmentIDs != nil {
		return mmSelectByAssignmentIDs.funcSelectByAssignmentIDs(ctx, assignmentIDs)
	}
	mmSelectByAssignmentIDs.t.Fatalf("Unexpected call to AssignmentTargetMock.SelectByAssignmentIDs. %v %v", ctx, assignmentIDs)
	return
}

// SelectByAssignmentIDsAfterCounter returns a count of finished AssignmentTargetMock.SelectByAssignmentIDs invocations
func (mmSelectByAssignmentIDs *AssignmentTargetMock) SelectByAssignmentIDsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByAssignmentIDs.afterSelectByAssignmentIDsCounter)
}

// SelectByAssignmentIDsBeforeCounter returns a count of AssignmentTargetMock.SelectByAssignmentIDs invocations
func (mmSelectByAssignmentIDs *AssignmentTargetMock) SelectByAssignmentIDsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByAssignmentIDs.beforeSelectByAssignmentIDsCounter)
}

// Calls returns a list of arguments used in each call to AssignmentTargetMock.SelectByAssignmentIDs.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectByAssignmentIDs *mAssignmentTargetMockSelectByAssignmentIDs) Calls() []*AssignmentTargetMockSelectByAssignmentIDsParams {
	mmSelectByAssignmentIDs.mutex.RLock()

	argCopy := make([]*AssignmentTargetMockSelectByAssignmentIDsParams, len(mmSelectByAssignmentIDs.callArgs))
	copy(argCopy, mmSelectByAssignmentIDs.callArgs)

	mmSelectByAssignmentIDs.mutex.RUnlock()

	return argCopy
}

// MinimockSelectByAssignmentIDsDone returns true if the count of the SelectByAssignmentIDs invocations corresponds
// the number of defined expectations
func (m *AssignmentTargetMock) MinimockSelectByAssignmentIDsDone() bool {
	if m.SelectByAssignmentIDsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectByAssignmentIDsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectByAssignmentIDsMock.invocationsDone()
}

// MinimockSelectByAssignmentIDsInspect logs each unmet expectation
func (m *AssignmentTargetMock) MinimockSelectByAssignmentIDsInspect() {
	for _, e := range m.SelectByAssignmentIDsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AssignmentTargetMock.SelectByAssignmentIDs at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectByAssignmentIDsCounter := mm_atomic.LoadUint64(&m.afterSelectByAssignmentIDsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectByAssignmentIDsMock.defaultExpectation != nil && afterSelectByAssignmentIDsCounter < 1 {
		if m.SelectByAssignmentIDsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AssignmentTargetMock.SelectByAssignmentIDs at\n%s", m.SelectByAssignmentIDsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AssignmentTargetMock.SelectByAssignmentIDs at\n%s with params: %#v", m.SelectByAssignmentIDsMock.defaultExpectation.expectationOrigins.origin, *m.SelectByAssignmentIDsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectByAssignmentIDs != nil && afterSelectByAssignmentIDsCounter < 1 {
		m.t.Errorf("Expected call to AssignmentTargetMock.SelectByAssignmentIDs at\n%s", m.funcSelectByAssignmentIDsOrigin)
	}

	if !m.SelectByAssignmentIDsMock.invocationsDone() && afterSelectByAssignmentIDsCounter > 0 {
		m.t.Errorf("Expected %d calls to AssignmentTargetMock.SelectByAssignmentIDs at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectByAssignmentIDsMock.expectedInvocations), m.SelectByAssignmentIDsMock.expectedInvocationsOrigin, afterSelectByAssignmentIDsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AssignmentTargetMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockInsertBatchInspect()

			m.MinimockSelectByAssignmentIDsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AssignmentTargetMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AssignmentTargetMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockInsertBatchDone() &&
		m.MinimockSelectByAssignmentIDsDone()
}
