// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package repository_mocks

//go:generate minimock -i vilib-api/internal/repository.GroupMember -o group_member_mock.go -n GroupMemberMock -p repository_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"vilib-api/internal/domain"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// GroupMemberMock implements mm_repository.GroupMember
type GroupMemberMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDelete          func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (err error)
	funcDeleteOrigin    string
	inspectFuncDelete   func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)
	afterDeleteCounter  uint64
	beforeDeleteCounter uint64
	DeleteMock          mGroupMemberMockDelete

	funcInsert          func(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID) (ga1 []domain.GroupMember, err error)
	funcInsertOrigin    string
	inspectFuncInsert   func(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID)
	afterInsertCounter  uint64
	beforeInsertCounter uint64
	InsertMock          mGroupMemberMockInsert

	funcSelectByUserIDAndGroupID          func(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (g1 domain.GroupMember, err error)
	funcSelectByUserIDAndGroupIDOrigin    string
	inspectFuncSelectByUserIDAndGroupID   func(ctx context.Context, userID uuid.UUID, groupID uuid.UUID)
	afterSelectByUserIDAndGroupIDCounter  uint64
	beforeSelectByUserIDAndGroupIDCounter uint64
	SelectByUserIDAndGroupIDMock          mGroupMemberMockSelectByUserIDAndGroupID
}

// NewGroupMemberMock returns a mock for mm_repository.GroupMember
func NewGroupMemberMock(t minimock.Tester) *GroupMemberMock {
	m := &GroupMemberMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteMock = mGroupMemberMockDelete{mock: m}
	m.DeleteMock.callArgs = []*GroupMemberMockDeleteParams{}

	m.InsertMock = mGroupMemberMockInsert{mock: m}
	m.InsertMock.callArgs = []*GroupMemberMockInsertParams{}

	m.SelectByUserIDAndGroupIDMock = mGroupMemberMockSelectByUserIDAndGroupID{mock: m}
	m.SelectByUserIDAndGroupIDMock.callArgs = []*GroupMemberMockSelectByUserIDAndGroupIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGroupMemberMockDelete struct {
	optional           bool
	mock               *GroupMemberMock
	defaultExpectation *GroupMemberMockDeleteExpectation
	expectations       []*GroupMemberMockDeleteExpectation

	callArgs []*GroupMemberMockDeleteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupMemberMockDeleteExpectation specifies expectation struct of the GroupMember.Delete
type GroupMemberMockDeleteExpectation struct {
	mock               *GroupMemberMock
	params             *GroupMemberMockDeleteParams
	paramPtrs          *GroupMemberMockDeleteParamPtrs
	expectationOrigins GroupMemberMockDeleteExpectationOrigins
	results            *GroupMemberMockDeleteResults
	returnOrigin       string
	Counter            uint64
}

// GroupMemberMockDeleteParams contains parameters of the GroupMember.Delete
type GroupMemberMockDeleteParams struct {
	ctx     context.Context
	groupID uuid.UUID
	userID  uuid.UUID
}

// GroupMemberMockDeleteParamPtrs contains pointers to parameters of the GroupMember.Delete
type GroupMemberMockDeleteParamPtrs struct {
	ctx     *context.Context
	groupID *uuid.UUID
	userID  *uuid.UUID
}

// GroupMemberMockDeleteResults contains results of the GroupMember.Delete
type GroupMemberMockDeleteResults struct {
	err error
}

// GroupMemberMockDeleteOrigins contains origins of expectations of the GroupMember.Delete
type GroupMemberMockDeleteExpectationOrigins struct {
	origin        string
	originCtx     string
	originGroupID string
	originUserID  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDelete *mGroupMemberMockDelete) Optional() *mGroupMemberMockDelete {
	mmDelete.optional = true
	return mmDelete
}

// Expect sets up expected params for GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) Expect(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) *mGroupMemberMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupMemberMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.paramPtrs != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by ExpectParams functions")
	}

	mmDelete.defaultExpectation.params = &GroupMemberMockDeleteParams{ctx, groupID, userID}
	mmDelete.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDelete.expectations {
		if minimock.Equal(e.params, mmDelete.defaultExpectation.params) {
			mmDelete.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDelete.defaultExpectation.params)
		}
	}

	return mmDelete
}

// ExpectCtxParam1 sets up expected param ctx for GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) ExpectCtxParam1(ctx context.Context) *mGroupMemberMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupMemberMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupMemberMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.ctx = &ctx
	mmDelete.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectGroupIDParam2 sets up expected param groupID for GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) ExpectGroupIDParam2(groupID uuid.UUID) *mGroupMemberMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupMemberMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupMemberMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.groupID = &groupID
	mmDelete.defaultExpectation.expectationOrigins.originGroupID = minimock.CallerInfo(1)

	return mmDelete
}

// ExpectUserIDParam3 sets up expected param userID for GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) ExpectUserIDParam3(userID uuid.UUID) *mGroupMemberMockDelete {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupMemberMockDeleteExpectation{}
	}

	if mmDelete.defaultExpectation.params != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Expect")
	}

	if mmDelete.defaultExpectation.paramPtrs == nil {
		mmDelete.defaultExpectation.paramPtrs = &GroupMemberMockDeleteParamPtrs{}
	}
	mmDelete.defaultExpectation.paramPtrs.userID = &userID
	mmDelete.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDelete
}

// Inspect accepts an inspector function that has same arguments as the GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) Inspect(f func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *mGroupMemberMockDelete {
	if mmDelete.mock.inspectFuncDelete != nil {
		mmDelete.mock.t.Fatalf("Inspect function is already set for GroupMemberMock.Delete")
	}

	mmDelete.mock.inspectFuncDelete = f

	return mmDelete
}

// Return sets up results that will be returned by GroupMember.Delete
func (mmDelete *mGroupMemberMockDelete) Return(err error) *GroupMemberMock {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	if mmDelete.defaultExpectation == nil {
		mmDelete.defaultExpectation = &GroupMemberMockDeleteExpectation{mock: mmDelete.mock}
	}
	mmDelete.defaultExpectation.results = &GroupMemberMockDeleteResults{err}
	mmDelete.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// Set uses given function f to mock the GroupMember.Delete method
func (mmDelete *mGroupMemberMockDelete) Set(f func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (err error)) *GroupMemberMock {
	if mmDelete.defaultExpectation != nil {
		mmDelete.mock.t.Fatalf("Default expectation is already set for the GroupMember.Delete method")
	}

	if len(mmDelete.expectations) > 0 {
		mmDelete.mock.t.Fatalf("Some expectations are already set for the GroupMember.Delete method")
	}

	mmDelete.mock.funcDelete = f
	mmDelete.mock.funcDeleteOrigin = minimock.CallerInfo(1)
	return mmDelete.mock
}

// When sets expectation for the GroupMember.Delete which will trigger the result defined by the following
// Then helper
func (mmDelete *mGroupMemberMockDelete) When(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) *GroupMemberMockDeleteExpectation {
	if mmDelete.mock.funcDelete != nil {
		mmDelete.mock.t.Fatalf("GroupMemberMock.Delete mock is already set by Set")
	}

	expectation := &GroupMemberMockDeleteExpectation{
		mock:               mmDelete.mock,
		params:             &GroupMemberMockDeleteParams{ctx, groupID, userID},
		expectationOrigins: GroupMemberMockDeleteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDelete.expectations = append(mmDelete.expectations, expectation)
	return expectation
}

// Then sets up GroupMember.Delete return parameters for the expectation previously defined by the When method
func (e *GroupMemberMockDeleteExpectation) Then(err error) *GroupMemberMock {
	e.results = &GroupMemberMockDeleteResults{err}
	return e.mock
}

// Times sets number of times GroupMember.Delete should be invoked
func (mmDelete *mGroupMemberMockDelete) Times(n uint64) *mGroupMemberMockDelete {
	if n == 0 {
		mmDelete.mock.t.Fatalf("Times of GroupMemberMock.Delete mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDelete.expectedInvocations, n)
	mmDelete.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDelete
}

func (mmDelete *mGroupMemberMockDelete) invocationsDone() bool {
	if len(mmDelete.expectations) == 0 && mmDelete.defaultExpectation == nil && mmDelete.mock.funcDelete == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDelete.mock.afterDeleteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDelete.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Delete implements mm_repository.GroupMember
func (mmDelete *GroupMemberMock) Delete(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (err error) {
	mm_atomic.AddUint64(&mmDelete.beforeDeleteCounter, 1)
	defer mm_atomic.AddUint64(&mmDelete.afterDeleteCounter, 1)

	mmDelete.t.Helper()

	if mmDelete.inspectFuncDelete != nil {
		mmDelete.inspectFuncDelete(ctx, groupID, userID)
	}

	mm_params := GroupMemberMockDeleteParams{ctx, groupID, userID}

	// Record call args
	mmDelete.DeleteMock.mutex.Lock()
	mmDelete.DeleteMock.callArgs = append(mmDelete.DeleteMock.callArgs, &mm_params)
	mmDelete.DeleteMock.mutex.Unlock()

	for _, e := range mmDelete.DeleteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDelete.DeleteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDelete.DeleteMock.defaultExpectation.Counter, 1)
		mm_want := mmDelete.DeleteMock.defaultExpectation.params
		mm_want_ptrs := mmDelete.DeleteMock.defaultExpectation.paramPtrs

		mm_got := GroupMemberMockDeleteParams{ctx, groupID, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDelete.t.Errorf("GroupMemberMock.Delete got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.groupID != nil && !minimock.Equal(*mm_want_ptrs.groupID, mm_got.groupID) {
				mmDelete.t.Errorf("GroupMemberMock.Delete got unexpected parameter groupID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originGroupID, *mm_want_ptrs.groupID, mm_got.groupID, minimock.Diff(*mm_want_ptrs.groupID, mm_got.groupID))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDelete.t.Errorf("GroupMemberMock.Delete got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDelete.DeleteMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDelete.t.Errorf("GroupMemberMock.Delete got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDelete.DeleteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDelete.DeleteMock.defaultExpectation.results
		if mm_results == nil {
			mmDelete.t.Fatal("No results are set for the GroupMemberMock.Delete")
		}
		return (*mm_results).err
	}
	if mmDelete.funcDelete != nil {
		return mmDelete.funcDelete(ctx, groupID, userID)
	}
	mmDelete.t.Fatalf("Unexpected call to GroupMemberMock.Delete. %v %v %v", ctx, groupID, userID)
	return
}

// DeleteAfterCounter returns a count of finished GroupMemberMock.Delete invocations
func (mmDelete *GroupMemberMock) DeleteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.afterDeleteCounter)
}

// DeleteBeforeCounter returns a count of GroupMemberMock.Delete invocations
func (mmDelete *GroupMemberMock) DeleteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDelete.beforeDeleteCounter)
}

// Calls returns a list of arguments used in each call to GroupMemberMock.Delete.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDelete *mGroupMemberMockDelete) Calls() []*GroupMemberMockDeleteParams {
	mmDelete.mutex.RLock()

	argCopy := make([]*GroupMemberMockDeleteParams, len(mmDelete.callArgs))
	copy(argCopy, mmDelete.callArgs)

	mmDelete.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteDone returns true if the count of the Delete invocations corresponds
// the number of defined expectations
func (m *GroupMemberMock) MinimockDeleteDone() bool {
	if m.DeleteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteMock.invocationsDone()
}

// MinimockDeleteInspect logs each unmet expectation
func (m *GroupMemberMock) MinimockDeleteInspect() {
	for _, e := range m.DeleteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupMemberMock.Delete at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteCounter := mm_atomic.LoadUint64(&m.afterDeleteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteMock.defaultExpectation != nil && afterDeleteCounter < 1 {
		if m.DeleteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupMemberMock.Delete at\n%s", m.DeleteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupMemberMock.Delete at\n%s with params: %#v", m.DeleteMock.defaultExpectation.expectationOrigins.origin, *m.DeleteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDelete != nil && afterDeleteCounter < 1 {
		m.t.Errorf("Expected call to GroupMemberMock.Delete at\n%s", m.funcDeleteOrigin)
	}

	if !m.DeleteMock.invocationsDone() && afterDeleteCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupMemberMock.Delete at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteMock.expectedInvocations), m.DeleteMock.expectedInvocationsOrigin, afterDeleteCounter)
	}
}

type mGroupMemberMockInsert struct {
	optional           bool
	mock               *GroupMemberMock
	defaultExpectation *GroupMemberMockInsertExpectation
	expectations       []*GroupMemberMockInsertExpectation

	callArgs []*GroupMemberMockInsertParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupMemberMockInsertExpectation specifies expectation struct of the GroupMember.Insert
type GroupMemberMockInsertExpectation struct {
	mock               *GroupMemberMock
	params             *GroupMemberMockInsertParams
	paramPtrs          *GroupMemberMockInsertParamPtrs
	expectationOrigins GroupMemberMockInsertExpectationOrigins
	results            *GroupMemberMockInsertResults
	returnOrigin       string
	Counter            uint64
}

// GroupMemberMockInsertParams contains parameters of the GroupMember.Insert
type GroupMemberMockInsertParams struct {
	ctx     context.Context
	groupID uuid.UUID
	roleID  uuid.UUID
	usersID []uuid.UUID
}

// GroupMemberMockInsertParamPtrs contains pointers to parameters of the GroupMember.Insert
type GroupMemberMockInsertParamPtrs struct {
	ctx     *context.Context
	groupID *uuid.UUID
	roleID  *uuid.UUID
	usersID *[]uuid.UUID
}

// GroupMemberMockInsertResults contains results of the GroupMember.Insert
type GroupMemberMockInsertResults struct {
	ga1 []domain.GroupMember
	err error
}

// GroupMemberMockInsertOrigins contains origins of expectations of the GroupMember.Insert
type GroupMemberMockInsertExpectationOrigins struct {
	origin        string
	originCtx     string
	originGroupID string
	originRoleID  string
	originUsersID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsert *mGroupMemberMockInsert) Optional() *mGroupMemberMockInsert {
	mmInsert.optional = true
	return mmInsert
}

// Expect sets up expected params for GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) Expect(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID) *mGroupMemberMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.paramPtrs != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by ExpectParams functions")
	}

	mmInsert.defaultExpectation.params = &GroupMemberMockInsertParams{ctx, groupID, roleID, usersID}
	mmInsert.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsert.expectations {
		if minimock.Equal(e.params, mmInsert.defaultExpectation.params) {
			mmInsert.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsert.defaultExpectation.params)
		}
	}

	return mmInsert
}

// ExpectCtxParam1 sets up expected param ctx for GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) ExpectCtxParam1(ctx context.Context) *mGroupMemberMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &GroupMemberMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsert.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectGroupIDParam2 sets up expected param groupID for GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) ExpectGroupIDParam2(groupID uuid.UUID) *mGroupMemberMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &GroupMemberMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.groupID = &groupID
	mmInsert.defaultExpectation.expectationOrigins.originGroupID = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectRoleIDParam3 sets up expected param roleID for GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) ExpectRoleIDParam3(roleID uuid.UUID) *mGroupMemberMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &GroupMemberMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.roleID = &roleID
	mmInsert.defaultExpectation.expectationOrigins.originRoleID = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectUsersIDParam4 sets up expected param usersID for GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) ExpectUsersIDParam4(usersID ...uuid.UUID) *mGroupMemberMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &GroupMemberMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.usersID = &usersID
	mmInsert.defaultExpectation.expectationOrigins.originUsersID = minimock.CallerInfo(1)

	return mmInsert
}

// Inspect accepts an inspector function that has same arguments as the GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) Inspect(f func(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID)) *mGroupMemberMockInsert {
	if mmInsert.mock.inspectFuncInsert != nil {
		mmInsert.mock.t.Fatalf("Inspect function is already set for GroupMemberMock.Insert")
	}

	mmInsert.mock.inspectFuncInsert = f

	return mmInsert
}

// Return sets up results that will be returned by GroupMember.Insert
func (mmInsert *mGroupMemberMockInsert) Return(ga1 []domain.GroupMember, err error) *GroupMemberMock {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &GroupMemberMockInsertExpectation{mock: mmInsert.mock}
	}
	mmInsert.defaultExpectation.results = &GroupMemberMockInsertResults{ga1, err}
	mmInsert.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// Set uses given function f to mock the GroupMember.Insert method
func (mmInsert *mGroupMemberMockInsert) Set(f func(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID) (ga1 []domain.GroupMember, err error)) *GroupMemberMock {
	if mmInsert.defaultExpectation != nil {
		mmInsert.mock.t.Fatalf("Default expectation is already set for the GroupMember.Insert method")
	}

	if len(mmInsert.expectations) > 0 {
		mmInsert.mock.t.Fatalf("Some expectations are already set for the GroupMember.Insert method")
	}

	mmInsert.mock.funcInsert = f
	mmInsert.mock.funcInsertOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// When sets expectation for the GroupMember.Insert which will trigger the result defined by the following
// Then helper
func (mmInsert *mGroupMemberMockInsert) When(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID) *GroupMemberMockInsertExpectation {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("GroupMemberMock.Insert mock is already set by Set")
	}

	expectation := &GroupMemberMockInsertExpectation{
		mock:               mmInsert.mock,
		params:             &GroupMemberMockInsertParams{ctx, groupID, roleID, usersID},
		expectationOrigins: GroupMemberMockInsertExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsert.expectations = append(mmInsert.expectations, expectation)
	return expectation
}

// Then sets up GroupMember.Insert return parameters for the expectation previously defined by the When method
func (e *GroupMemberMockInsertExpectation) Then(ga1 []domain.GroupMember, err error) *GroupMemberMock {
	e.results = &GroupMemberMockInsertResults{ga1, err}
	return e.mock
}

// Times sets number of times GroupMember.Insert should be invoked
func (mmInsert *mGroupMemberMockInsert) Times(n uint64) *mGroupMemberMockInsert {
	if n == 0 {
		mmInsert.mock.t.Fatalf("Times of GroupMemberMock.Insert mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsert.expectedInvocations, n)
	mmInsert.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsert
}

func (mmInsert *mGroupMemberMockInsert) invocationsDone() bool {
	if len(mmInsert.expectations) == 0 && mmInsert.defaultExpectation == nil && mmInsert.mock.funcInsert == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsert.mock.afterInsertCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsert.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Insert implements mm_repository.GroupMember
func (mmInsert *GroupMemberMock) Insert(ctx context.Context, groupID uuid.UUID, roleID uuid.UUID, usersID ...uuid.UUID) (ga1 []domain.GroupMember, err error) {
	mm_atomic.AddUint64(&mmInsert.beforeInsertCounter, 1)
	defer mm_atomic.AddUint64(&mmInsert.afterInsertCounter, 1)

	mmInsert.t.Helper()

	if mmInsert.inspectFuncInsert != nil {
		mmInsert.inspectFuncInsert(ctx, groupID, roleID, usersID...)
	}

	mm_params := GroupMemberMockInsertParams{ctx, groupID, roleID, usersID}

	// Record call args
	mmInsert.InsertMock.mutex.Lock()
	mmInsert.InsertMock.callArgs = append(mmInsert.InsertMock.callArgs, &mm_params)
	mmInsert.InsertMock.mutex.Unlock()

	for _, e := range mmInsert.InsertMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ga1, e.results.err
		}
	}

	if mmInsert.InsertMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsert.InsertMock.defaultExpectation.Counter, 1)
		mm_want := mmInsert.InsertMock.defaultExpectation.params
		mm_want_ptrs := mmInsert.InsertMock.defaultExpectation.paramPtrs

		mm_got := GroupMemberMockInsertParams{ctx, groupID, roleID, usersID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsert.t.Errorf("GroupMemberMock.Insert got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.groupID != nil && !minimock.Equal(*mm_want_ptrs.groupID, mm_got.groupID) {
				mmInsert.t.Errorf("GroupMemberMock.Insert got unexpected parameter groupID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originGroupID, *mm_want_ptrs.groupID, mm_got.groupID, minimock.Diff(*mm_want_ptrs.groupID, mm_got.groupID))
			}

			if mm_want_ptrs.roleID != nil && !minimock.Equal(*mm_want_ptrs.roleID, mm_got.roleID) {
				mmInsert.t.Errorf("GroupMemberMock.Insert got unexpected parameter roleID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originRoleID, *mm_want_ptrs.roleID, mm_got.roleID, minimock.Diff(*mm_want_ptrs.roleID, mm_got.roleID))
			}

			if mm_want_ptrs.usersID != nil && !minimock.Equal(*mm_want_ptrs.usersID, mm_got.usersID) {
				mmInsert.t.Errorf("GroupMemberMock.Insert got unexpected parameter usersID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originUsersID, *mm_want_ptrs.usersID, mm_got.usersID, minimock.Diff(*mm_want_ptrs.usersID, mm_got.usersID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsert.t.Errorf("GroupMemberMock.Insert got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsert.InsertMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsert.InsertMock.defaultExpectation.results
		if mm_results == nil {
			mmInsert.t.Fatal("No results are set for the GroupMemberMock.Insert")
		}
		return (*mm_results).ga1, (*mm_results).err
	}
	if mmInsert.funcInsert != nil {
		return mmInsert.funcInsert(ctx, groupID, roleID, usersID...)
	}
	mmInsert.t.Fatalf("Unexpected call to GroupMemberMock.Insert. %v %v %v %v", ctx, groupID, roleID, usersID)
	return
}

// InsertAfterCounter returns a count of finished GroupMemberMock.Insert invocations
func (mmInsert *GroupMemberMock) InsertAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.afterInsertCounter)
}

// InsertBeforeCounter returns a count of GroupMemberMock.Insert invocations
func (mmInsert *GroupMemberMock) InsertBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.beforeInsertCounter)
}

// Calls returns a list of arguments used in each call to GroupMemberMock.Insert.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsert *mGroupMemberMockInsert) Calls() []*GroupMemberMockInsertParams {
	mmInsert.mutex.RLock()

	argCopy := make([]*GroupMemberMockInsertParams, len(mmInsert.callArgs))
	copy(argCopy, mmInsert.callArgs)

	mmInsert.mutex.RUnlock()

	return argCopy
}

// MinimockInsertDone returns true if the count of the Insert invocations corresponds
// the number of defined expectations
func (m *GroupMemberMock) MinimockInsertDone() bool {
	if m.InsertMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertMock.invocationsDone()
}

// MinimockInsertInspect logs each unmet expectation
func (m *GroupMemberMock) MinimockInsertInspect() {
	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupMemberMock.Insert at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertCounter := mm_atomic.LoadUint64(&m.afterInsertCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertMock.defaultExpectation != nil && afterInsertCounter < 1 {
		if m.InsertMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupMemberMock.Insert at\n%s", m.InsertMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupMemberMock.Insert at\n%s with params: %#v", m.InsertMock.defaultExpectation.expectationOrigins.origin, *m.InsertMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsert != nil && afterInsertCounter < 1 {
		m.t.Errorf("Expected call to GroupMemberMock.Insert at\n%s", m.funcInsertOrigin)
	}

	if !m.InsertMock.invocationsDone() && afterInsertCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupMemberMock.Insert at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertMock.expectedInvocations), m.InsertMock.expectedInvocationsOrigin, afterInsertCounter)
	}
}

type mGroupMemberMockSelectByUserIDAndGroupID struct {
	optional           bool
	mock               *GroupMemberMock
	defaultExpectation *GroupMemberMockSelectByUserIDAndGroupIDExpectation
	expectations       []*GroupMemberMockSelectByUserIDAndGroupIDExpectation

	callArgs []*GroupMemberMockSelectByUserIDAndGroupIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GroupMemberMockSelectByUserIDAndGroupIDExpectation specifies expectation struct of the GroupMember.SelectByUserIDAndGroupID
type GroupMemberMockSelectByUserIDAndGroupIDExpectation struct {
	mock               *GroupMemberMock
	params             *GroupMemberMockSelectByUserIDAndGroupIDParams
	paramPtrs          *GroupMemberMockSelectByUserIDAndGroupIDParamPtrs
	expectationOrigins GroupMemberMockSelectByUserIDAndGroupIDExpectationOrigins
	results            *GroupMemberMockSelectByUserIDAndGroupIDResults
	returnOrigin       string
	Counter            uint64
}

// GroupMemberMockSelectByUserIDAndGroupIDParams contains parameters of the GroupMember.SelectByUserIDAndGroupID
type GroupMemberMockSelectByUserIDAndGroupIDParams struct {
	ctx     context.Context
	userID  uuid.UUID
	groupID uuid.UUID
}

// GroupMemberMockSelectByUserIDAndGroupIDParamPtrs contains pointers to parameters of the GroupMember.SelectByUserIDAndGroupID
type GroupMemberMockSelectByUserIDAndGroupIDParamPtrs struct {
	ctx     *context.Context
	userID  *uuid.UUID
	groupID *uuid.UUID
}

// GroupMemberMockSelectByUserIDAndGroupIDResults contains results of the GroupMember.SelectByUserIDAndGroupID
type GroupMemberMockSelectByUserIDAndGroupIDResults struct {
	g1  domain.GroupMember
	err error
}

// GroupMemberMockSelectByUserIDAndGroupIDOrigins contains origins of expectations of the GroupMember.SelectByUserIDAndGroupID
type GroupMemberMockSelectByUserIDAndGroupIDExpectationOrigins struct {
	origin        string
	originCtx     string
	originUserID  string
	originGroupID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Optional() *mGroupMemberMockSelectByUserIDAndGroupID {
	mmSelectByUserIDAndGroupID.optional = true
	return mmSelectByUserIDAndGroupID
}

// Expect sets up expected params for GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Expect(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) *mGroupMemberMockSelectByUserIDAndGroupID {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation = &GroupMemberMockSelectByUserIDAndGroupIDExpectation{}
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by ExpectParams functions")
	}

	mmSelectByUserIDAndGroupID.defaultExpectation.params = &GroupMemberMockSelectByUserIDAndGroupIDParams{ctx, userID, groupID}
	mmSelectByUserIDAndGroupID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectByUserIDAndGroupID.expectations {
		if minimock.Equal(e.params, mmSelectByUserIDAndGroupID.defaultExpectation.params) {
			mmSelectByUserIDAndGroupID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectByUserIDAndGroupID.defaultExpectation.params)
		}
	}

	return mmSelectByUserIDAndGroupID
}

// ExpectCtxParam1 sets up expected param ctx for GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) ExpectCtxParam1(ctx context.Context) *mGroupMemberMockSelectByUserIDAndGroupID {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation = &GroupMemberMockSelectByUserIDAndGroupIDExpectation{}
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.params != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Expect")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs = &GroupMemberMockSelectByUserIDAndGroupIDParamPtrs{}
	}
	mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectByUserIDAndGroupID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectByUserIDAndGroupID
}

// ExpectUserIDParam2 sets up expected param userID for GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) ExpectUserIDParam2(userID uuid.UUID) *mGroupMemberMockSelectByUserIDAndGroupID {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation = &GroupMemberMockSelectByUserIDAndGroupIDExpectation{}
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.params != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Expect")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs = &GroupMemberMockSelectByUserIDAndGroupIDParamPtrs{}
	}
	mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs.userID = &userID
	mmSelectByUserIDAndGroupID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSelectByUserIDAndGroupID
}

// ExpectGroupIDParam3 sets up expected param groupID for GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) ExpectGroupIDParam3(groupID uuid.UUID) *mGroupMemberMockSelectByUserIDAndGroupID {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation = &GroupMemberMockSelectByUserIDAndGroupIDExpectation{}
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.params != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Expect")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs = &GroupMemberMockSelectByUserIDAndGroupIDParamPtrs{}
	}
	mmSelectByUserIDAndGroupID.defaultExpectation.paramPtrs.groupID = &groupID
	mmSelectByUserIDAndGroupID.defaultExpectation.expectationOrigins.originGroupID = minimock.CallerInfo(1)

	return mmSelectByUserIDAndGroupID
}

// Inspect accepts an inspector function that has same arguments as the GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Inspect(f func(ctx context.Context, userID uuid.UUID, groupID uuid.UUID)) *mGroupMemberMockSelectByUserIDAndGroupID {
	if mmSelectByUserIDAndGroupID.mock.inspectFuncSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("Inspect function is already set for GroupMemberMock.SelectByUserIDAndGroupID")
	}

	mmSelectByUserIDAndGroupID.mock.inspectFuncSelectByUserIDAndGroupID = f

	return mmSelectByUserIDAndGroupID
}

// Return sets up results that will be returned by GroupMember.SelectByUserIDAndGroupID
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Return(g1 domain.GroupMember, err error) *GroupMemberMock {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	if mmSelectByUserIDAndGroupID.defaultExpectation == nil {
		mmSelectByUserIDAndGroupID.defaultExpectation = &GroupMemberMockSelectByUserIDAndGroupIDExpectation{mock: mmSelectByUserIDAndGroupID.mock}
	}
	mmSelectByUserIDAndGroupID.defaultExpectation.results = &GroupMemberMockSelectByUserIDAndGroupIDResults{g1, err}
	mmSelectByUserIDAndGroupID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectByUserIDAndGroupID.mock
}

// Set uses given function f to mock the GroupMember.SelectByUserIDAndGroupID method
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Set(f func(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (g1 domain.GroupMember, err error)) *GroupMemberMock {
	if mmSelectByUserIDAndGroupID.defaultExpectation != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("Default expectation is already set for the GroupMember.SelectByUserIDAndGroupID method")
	}

	if len(mmSelectByUserIDAndGroupID.expectations) > 0 {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("Some expectations are already set for the GroupMember.SelectByUserIDAndGroupID method")
	}

	mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID = f
	mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupIDOrigin = minimock.CallerInfo(1)
	return mmSelectByUserIDAndGroupID.mock
}

// When sets expectation for the GroupMember.SelectByUserIDAndGroupID which will trigger the result defined by the following
// Then helper
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) When(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) *GroupMemberMockSelectByUserIDAndGroupIDExpectation {
	if mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("GroupMemberMock.SelectByUserIDAndGroupID mock is already set by Set")
	}

	expectation := &GroupMemberMockSelectByUserIDAndGroupIDExpectation{
		mock:               mmSelectByUserIDAndGroupID.mock,
		params:             &GroupMemberMockSelectByUserIDAndGroupIDParams{ctx, userID, groupID},
		expectationOrigins: GroupMemberMockSelectByUserIDAndGroupIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectByUserIDAndGroupID.expectations = append(mmSelectByUserIDAndGroupID.expectations, expectation)
	return expectation
}

// Then sets up GroupMember.SelectByUserIDAndGroupID return parameters for the expectation previously defined by the When method
func (e *GroupMemberMockSelectByUserIDAndGroupIDExpectation) Then(g1 domain.GroupMember, err error) *GroupMemberMock {
	e.results = &GroupMemberMockSelectByUserIDAndGroupIDResults{g1, err}
	return e.mock
}

// Times sets number of times GroupMember.SelectByUserIDAndGroupID should be invoked
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Times(n uint64) *mGroupMemberMockSelectByUserIDAndGroupID {
	if n == 0 {
		mmSelectByUserIDAndGroupID.mock.t.Fatalf("Times of GroupMemberMock.SelectByUserIDAndGroupID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectByUserIDAndGroupID.expectedInvocations, n)
	mmSelectByUserIDAndGroupID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectByUserIDAndGroupID
}

func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) invocationsDone() bool {
	if len(mmSelectByUserIDAndGroupID.expectations) == 0 && mmSelectByUserIDAndGroupID.defaultExpectation == nil && mmSelectByUserIDAndGroupID.mock.funcSelectByUserIDAndGroupID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectByUserIDAndGroupID.mock.afterSelectByUserIDAndGroupIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectByUserIDAndGroupID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectByUserIDAndGroupID implements mm_repository.GroupMember
func (mmSelectByUserIDAndGroupID *GroupMemberMock) SelectByUserIDAndGroupID(ctx context.Context, userID uuid.UUID, groupID uuid.UUID) (g1 domain.GroupMember, err error) {
	mm_atomic.AddUint64(&mmSelectByUserIDAndGroupID.beforeSelectByUserIDAndGroupIDCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectByUserIDAndGroupID.afterSelectByUserIDAndGroupIDCounter, 1)

	mmSelectByUserIDAndGroupID.t.Helper()

	if mmSelectByUserIDAndGroupID.inspectFuncSelectByUserIDAndGroupID != nil {
		mmSelectByUserIDAndGroupID.inspectFuncSelectByUserIDAndGroupID(ctx, userID, groupID)
	}

	mm_params := GroupMemberMockSelectByUserIDAndGroupIDParams{ctx, userID, groupID}

	// Record call args
	mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.mutex.Lock()
	mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.callArgs = append(mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.callArgs, &mm_params)
	mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.mutex.Unlock()

	for _, e := range mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.g1, e.results.err
		}
	}

	if mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.params
		mm_want_ptrs := mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.paramPtrs

		mm_got := GroupMemberMockSelectByUserIDAndGroupIDParams{ctx, userID, groupID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectByUserIDAndGroupID.t.Errorf("GroupMemberMock.SelectByUserIDAndGroupID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSelectByUserIDAndGroupID.t.Errorf("GroupMemberMock.SelectByUserIDAndGroupID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.groupID != nil && !minimock.Equal(*mm_want_ptrs.groupID, mm_got.groupID) {
				mmSelectByUserIDAndGroupID.t.Errorf("GroupMemberMock.SelectByUserIDAndGroupID got unexpected parameter groupID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.expectationOrigins.originGroupID, *mm_want_ptrs.groupID, mm_got.groupID, minimock.Diff(*mm_want_ptrs.groupID, mm_got.groupID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectByUserIDAndGroupID.t.Errorf("GroupMemberMock.SelectByUserIDAndGroupID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectByUserIDAndGroupID.SelectByUserIDAndGroupIDMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectByUserIDAndGroupID.t.Fatal("No results are set for the GroupMemberMock.SelectByUserIDAndGroupID")
		}
		return (*mm_results).g1, (*mm_results).err
	}
	if mmSelectByUserIDAndGroupID.funcSelectByUserIDAndGroupID != nil {
		return mmSelectByUserIDAndGroupID.funcSelectByUserIDAndGroupID(ctx, userID, groupID)
	}
	mmSelectByUserIDAndGroupID.t.Fatalf("Unexpected call to GroupMemberMock.SelectByUserIDAndGroupID. %v %v %v", ctx, userID, groupID)
	return
}

// SelectByUserIDAndGroupIDAfterCounter returns a count of finished GroupMemberMock.SelectByUserIDAndGroupID invocations
func (mmSelectByUserIDAndGroupID *GroupMemberMock) SelectByUserIDAndGroupIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByUserIDAndGroupID.afterSelectByUserIDAndGroupIDCounter)
}

// SelectByUserIDAndGroupIDBeforeCounter returns a count of GroupMemberMock.SelectByUserIDAndGroupID invocations
func (mmSelectByUserIDAndGroupID *GroupMemberMock) SelectByUserIDAndGroupIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByUserIDAndGroupID.beforeSelectByUserIDAndGroupIDCounter)
}

// Calls returns a list of arguments used in each call to GroupMemberMock.SelectByUserIDAndGroupID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectByUserIDAndGroupID *mGroupMemberMockSelectByUserIDAndGroupID) Calls() []*GroupMemberMockSelectByUserIDAndGroupIDParams {
	mmSelectByUserIDAndGroupID.mutex.RLock()

	argCopy := make([]*GroupMemberMockSelectByUserIDAndGroupIDParams, len(mmSelectByUserIDAndGroupID.callArgs))
	copy(argCopy, mmSelectByUserIDAndGroupID.callArgs)

	mmSelectByUserIDAndGroupID.mutex.RUnlock()

	return argCopy
}

// MinimockSelectByUserIDAndGroupIDDone returns true if the count of the SelectByUserIDAndGroupID invocations corresponds
// the number of defined expectations
func (m *GroupMemberMock) MinimockSelectByUserIDAndGroupIDDone() bool {
	if m.SelectByUserIDAndGroupIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectByUserIDAndGroupIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectByUserIDAndGroupIDMock.invocationsDone()
}

// MinimockSelectByUserIDAndGroupIDInspect logs each unmet expectation
func (m *GroupMemberMock) MinimockSelectByUserIDAndGroupIDInspect() {
	for _, e := range m.SelectByUserIDAndGroupIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GroupMemberMock.SelectByUserIDAndGroupID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectByUserIDAndGroupIDCounter := mm_atomic.LoadUint64(&m.afterSelectByUserIDAndGroupIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectByUserIDAndGroupIDMock.defaultExpectation != nil && afterSelectByUserIDAndGroupIDCounter < 1 {
		if m.SelectByUserIDAndGroupIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GroupMemberMock.SelectByUserIDAndGroupID at\n%s", m.SelectByUserIDAndGroupIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GroupMemberMock.SelectByUserIDAndGroupID at\n%s with params: %#v", m.SelectByUserIDAndGroupIDMock.defaultExpectation.expectationOrigins.origin, *m.SelectByUserIDAndGroupIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectByUserIDAndGroupID != nil && afterSelectByUserIDAndGroupIDCounter < 1 {
		m.t.Errorf("Expected call to GroupMemberMock.SelectByUserIDAndGroupID at\n%s", m.funcSelectByUserIDAndGroupIDOrigin)
	}

	if !m.SelectByUserIDAndGroupIDMock.invocationsDone() && afterSelectByUserIDAndGroupIDCounter > 0 {
		m.t.Errorf("Expected %d calls to GroupMemberMock.SelectByUserIDAndGroupID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectByUserIDAndGroupIDMock.expectedInvocations), m.SelectByUserIDAndGroupIDMock.expectedInvocationsOrigin, afterSelectByUserIDAndGroupIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GroupMemberMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteInspect()

			m.MinimockInsertInspect()

			m.MinimockSelectByUserIDAndGroupIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GroupMemberMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GroupMemberMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteDone() &&
		m.MinimockInsertDone() &&
		m.MinimockSelectByUserIDAndGroupIDDone()
}
