// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package repository_mocks

//go:generate minimock -i vilib-api/internal/repository.User -o user_mock.go -n UserMock -p repository_mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"vilib-api/internal/domain"

	"github.com/gojuno/minimock/v3"
	"github.com/google/uuid"
)

// UserMock implements mm_repository.User
type UserMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcInsert          func(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID) (u1 domain.User, err error)
	funcInsertOrigin    string
	inspectFuncInsert   func(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID)
	afterInsertCounter  uint64
	beforeInsertCounter uint64
	InsertMock          mUserMockInsert

	funcSelectByEmail          func(ctx context.Context, email string) (ua1 []domain.User, err error)
	funcSelectByEmailOrigin    string
	inspectFuncSelectByEmail   func(ctx context.Context, email string)
	afterSelectByEmailCounter  uint64
	beforeSelectByEmailCounter uint64
	SelectByEmailMock          mUserMockSelectByEmail

	funcSelectByID          func(ctx context.Context, usersID ...uuid.UUID) (ua1 []domain.User, err error)
	funcSelectByIDOrigin    string
	inspectFuncSelectByID   func(ctx context.Context, usersID ...uuid.UUID)
	afterSelectByIDCounter  uint64
	beforeSelectByIDCounter uint64
	SelectByIDMock          mUserMockSelectByID
}

// NewUserMock returns a mock for mm_repository.User
func NewUserMock(t minimock.Tester) *UserMock {
	m := &UserMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.InsertMock = mUserMockInsert{mock: m}
	m.InsertMock.callArgs = []*UserMockInsertParams{}

	m.SelectByEmailMock = mUserMockSelectByEmail{mock: m}
	m.SelectByEmailMock.callArgs = []*UserMockSelectByEmailParams{}

	m.SelectByIDMock = mUserMockSelectByID{mock: m}
	m.SelectByIDMock.callArgs = []*UserMockSelectByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserMockInsert struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockInsertExpectation
	expectations       []*UserMockInsertExpectation

	callArgs []*UserMockInsertParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockInsertExpectation specifies expectation struct of the User.Insert
type UserMockInsertExpectation struct {
	mock               *UserMock
	params             *UserMockInsertParams
	paramPtrs          *UserMockInsertParamPtrs
	expectationOrigins UserMockInsertExpectationOrigins
	results            *UserMockInsertResults
	returnOrigin       string
	Counter            uint64
}

// UserMockInsertParams contains parameters of the User.Insert
type UserMockInsertParams struct {
	ctx     context.Context
	name    string
	surname string
	hash    string
	email   string
	roleID  uuid.UUID
}

// UserMockInsertParamPtrs contains pointers to parameters of the User.Insert
type UserMockInsertParamPtrs struct {
	ctx     *context.Context
	name    *string
	surname *string
	hash    *string
	email   *string
	roleID  *uuid.UUID
}

// UserMockInsertResults contains results of the User.Insert
type UserMockInsertResults struct {
	u1  domain.User
	err error
}

// UserMockInsertOrigins contains origins of expectations of the User.Insert
type UserMockInsertExpectationOrigins struct {
	origin        string
	originCtx     string
	originName    string
	originSurname string
	originHash    string
	originEmail   string
	originRoleID  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInsert *mUserMockInsert) Optional() *mUserMockInsert {
	mmInsert.optional = true
	return mmInsert
}

// Expect sets up expected params for User.Insert
func (mmInsert *mUserMockInsert) Expect(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.paramPtrs != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by ExpectParams functions")
	}

	mmInsert.defaultExpectation.params = &UserMockInsertParams{ctx, name, surname, hash, email, roleID}
	mmInsert.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInsert.expectations {
		if minimock.Equal(e.params, mmInsert.defaultExpectation.params) {
			mmInsert.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInsert.defaultExpectation.params)
		}
	}

	return mmInsert
}

// ExpectCtxParam1 sets up expected param ctx for User.Insert
func (mmInsert *mUserMockInsert) ExpectCtxParam1(ctx context.Context) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.ctx = &ctx
	mmInsert.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectNameParam2 sets up expected param name for User.Insert
func (mmInsert *mUserMockInsert) ExpectNameParam2(name string) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.name = &name
	mmInsert.defaultExpectation.expectationOrigins.originName = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectSurnameParam3 sets up expected param surname for User.Insert
func (mmInsert *mUserMockInsert) ExpectSurnameParam3(surname string) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.surname = &surname
	mmInsert.defaultExpectation.expectationOrigins.originSurname = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectHashParam4 sets up expected param hash for User.Insert
func (mmInsert *mUserMockInsert) ExpectHashParam4(hash string) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.hash = &hash
	mmInsert.defaultExpectation.expectationOrigins.originHash = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectEmailParam5 sets up expected param email for User.Insert
func (mmInsert *mUserMockInsert) ExpectEmailParam5(email string) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.email = &email
	mmInsert.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmInsert
}

// ExpectRoleIDParam6 sets up expected param roleID for User.Insert
func (mmInsert *mUserMockInsert) ExpectRoleIDParam6(roleID uuid.UUID) *mUserMockInsert {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{}
	}

	if mmInsert.defaultExpectation.params != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Expect")
	}

	if mmInsert.defaultExpectation.paramPtrs == nil {
		mmInsert.defaultExpectation.paramPtrs = &UserMockInsertParamPtrs{}
	}
	mmInsert.defaultExpectation.paramPtrs.roleID = &roleID
	mmInsert.defaultExpectation.expectationOrigins.originRoleID = minimock.CallerInfo(1)

	return mmInsert
}

// Inspect accepts an inspector function that has same arguments as the User.Insert
func (mmInsert *mUserMockInsert) Inspect(f func(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID)) *mUserMockInsert {
	if mmInsert.mock.inspectFuncInsert != nil {
		mmInsert.mock.t.Fatalf("Inspect function is already set for UserMock.Insert")
	}

	mmInsert.mock.inspectFuncInsert = f

	return mmInsert
}

// Return sets up results that will be returned by User.Insert
func (mmInsert *mUserMockInsert) Return(u1 domain.User, err error) *UserMock {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	if mmInsert.defaultExpectation == nil {
		mmInsert.defaultExpectation = &UserMockInsertExpectation{mock: mmInsert.mock}
	}
	mmInsert.defaultExpectation.results = &UserMockInsertResults{u1, err}
	mmInsert.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// Set uses given function f to mock the User.Insert method
func (mmInsert *mUserMockInsert) Set(f func(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID) (u1 domain.User, err error)) *UserMock {
	if mmInsert.defaultExpectation != nil {
		mmInsert.mock.t.Fatalf("Default expectation is already set for the User.Insert method")
	}

	if len(mmInsert.expectations) > 0 {
		mmInsert.mock.t.Fatalf("Some expectations are already set for the User.Insert method")
	}

	mmInsert.mock.funcInsert = f
	mmInsert.mock.funcInsertOrigin = minimock.CallerInfo(1)
	return mmInsert.mock
}

// When sets expectation for the User.Insert which will trigger the result defined by the following
// Then helper
func (mmInsert *mUserMockInsert) When(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID) *UserMockInsertExpectation {
	if mmInsert.mock.funcInsert != nil {
		mmInsert.mock.t.Fatalf("UserMock.Insert mock is already set by Set")
	}

	expectation := &UserMockInsertExpectation{
		mock:               mmInsert.mock,
		params:             &UserMockInsertParams{ctx, name, surname, hash, email, roleID},
		expectationOrigins: UserMockInsertExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInsert.expectations = append(mmInsert.expectations, expectation)
	return expectation
}

// Then sets up User.Insert return parameters for the expectation previously defined by the When method
func (e *UserMockInsertExpectation) Then(u1 domain.User, err error) *UserMock {
	e.results = &UserMockInsertResults{u1, err}
	return e.mock
}

// Times sets number of times User.Insert should be invoked
func (mmInsert *mUserMockInsert) Times(n uint64) *mUserMockInsert {
	if n == 0 {
		mmInsert.mock.t.Fatalf("Times of UserMock.Insert mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInsert.expectedInvocations, n)
	mmInsert.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInsert
}

func (mmInsert *mUserMockInsert) invocationsDone() bool {
	if len(mmInsert.expectations) == 0 && mmInsert.defaultExpectation == nil && mmInsert.mock.funcInsert == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInsert.mock.afterInsertCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInsert.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Insert implements mm_repository.User
func (mmInsert *UserMock) Insert(ctx context.Context, name string, surname string, hash string, email string, roleID uuid.UUID) (u1 domain.User, err error) {
	mm_atomic.AddUint64(&mmInsert.beforeInsertCounter, 1)
	defer mm_atomic.AddUint64(&mmInsert.afterInsertCounter, 1)

	mmInsert.t.Helper()

	if mmInsert.inspectFuncInsert != nil {
		mmInsert.inspectFuncInsert(ctx, name, surname, hash, email, roleID)
	}

	mm_params := UserMockInsertParams{ctx, name, surname, hash, email, roleID}

	// Record call args
	mmInsert.InsertMock.mutex.Lock()
	mmInsert.InsertMock.callArgs = append(mmInsert.InsertMock.callArgs, &mm_params)
	mmInsert.InsertMock.mutex.Unlock()

	for _, e := range mmInsert.InsertMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmInsert.InsertMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInsert.InsertMock.defaultExpectation.Counter, 1)
		mm_want := mmInsert.InsertMock.defaultExpectation.params
		mm_want_ptrs := mmInsert.InsertMock.defaultExpectation.paramPtrs

		mm_got := UserMockInsertParams{ctx, name, surname, hash, email, roleID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.name != nil && !minimock.Equal(*mm_want_ptrs.name, mm_got.name) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter name, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originName, *mm_want_ptrs.name, mm_got.name, minimock.Diff(*mm_want_ptrs.name, mm_got.name))
			}

			if mm_want_ptrs.surname != nil && !minimock.Equal(*mm_want_ptrs.surname, mm_got.surname) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter surname, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originSurname, *mm_want_ptrs.surname, mm_got.surname, minimock.Diff(*mm_want_ptrs.surname, mm_got.surname))
			}

			if mm_want_ptrs.hash != nil && !minimock.Equal(*mm_want_ptrs.hash, mm_got.hash) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter hash, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originHash, *mm_want_ptrs.hash, mm_got.hash, minimock.Diff(*mm_want_ptrs.hash, mm_got.hash))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.roleID != nil && !minimock.Equal(*mm_want_ptrs.roleID, mm_got.roleID) {
				mmInsert.t.Errorf("UserMock.Insert got unexpected parameter roleID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInsert.InsertMock.defaultExpectation.expectationOrigins.originRoleID, *mm_want_ptrs.roleID, mm_got.roleID, minimock.Diff(*mm_want_ptrs.roleID, mm_got.roleID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInsert.t.Errorf("UserMock.Insert got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInsert.InsertMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInsert.InsertMock.defaultExpectation.results
		if mm_results == nil {
			mmInsert.t.Fatal("No results are set for the UserMock.Insert")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmInsert.funcInsert != nil {
		return mmInsert.funcInsert(ctx, name, surname, hash, email, roleID)
	}
	mmInsert.t.Fatalf("Unexpected call to UserMock.Insert. %v %v %v %v %v %v", ctx, name, surname, hash, email, roleID)
	return
}

// InsertAfterCounter returns a count of finished UserMock.Insert invocations
func (mmInsert *UserMock) InsertAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.afterInsertCounter)
}

// InsertBeforeCounter returns a count of UserMock.Insert invocations
func (mmInsert *UserMock) InsertBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInsert.beforeInsertCounter)
}

// Calls returns a list of arguments used in each call to UserMock.Insert.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInsert *mUserMockInsert) Calls() []*UserMockInsertParams {
	mmInsert.mutex.RLock()

	argCopy := make([]*UserMockInsertParams, len(mmInsert.callArgs))
	copy(argCopy, mmInsert.callArgs)

	mmInsert.mutex.RUnlock()

	return argCopy
}

// MinimockInsertDone returns true if the count of the Insert invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockInsertDone() bool {
	if m.InsertMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InsertMock.invocationsDone()
}

// MinimockInsertInspect logs each unmet expectation
func (m *UserMock) MinimockInsertInspect() {
	for _, e := range m.InsertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.Insert at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInsertCounter := mm_atomic.LoadUint64(&m.afterInsertCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InsertMock.defaultExpectation != nil && afterInsertCounter < 1 {
		if m.InsertMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.Insert at\n%s", m.InsertMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.Insert at\n%s with params: %#v", m.InsertMock.defaultExpectation.expectationOrigins.origin, *m.InsertMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInsert != nil && afterInsertCounter < 1 {
		m.t.Errorf("Expected call to UserMock.Insert at\n%s", m.funcInsertOrigin)
	}

	if !m.InsertMock.invocationsDone() && afterInsertCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.Insert at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InsertMock.expectedInvocations), m.InsertMock.expectedInvocationsOrigin, afterInsertCounter)
	}
}

type mUserMockSelectByEmail struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockSelectByEmailExpectation
	expectations       []*UserMockSelectByEmailExpectation

	callArgs []*UserMockSelectByEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockSelectByEmailExpectation specifies expectation struct of the User.SelectByEmail
type UserMockSelectByEmailExpectation struct {
	mock               *UserMock
	params             *UserMockSelectByEmailParams
	paramPtrs          *UserMockSelectByEmailParamPtrs
	expectationOrigins UserMockSelectByEmailExpectationOrigins
	results            *UserMockSelectByEmailResults
	returnOrigin       string
	Counter            uint64
}

// UserMockSelectByEmailParams contains parameters of the User.SelectByEmail
type UserMockSelectByEmailParams struct {
	ctx   context.Context
	email string
}

// UserMockSelectByEmailParamPtrs contains pointers to parameters of the User.SelectByEmail
type UserMockSelectByEmailParamPtrs struct {
	ctx   *context.Context
	email *string
}

// UserMockSelectByEmailResults contains results of the User.SelectByEmail
type UserMockSelectByEmailResults struct {
	ua1 []domain.User
	err error
}

// UserMockSelectByEmailOrigins contains origins of expectations of the User.SelectByEmail
type UserMockSelectByEmailExpectationOrigins struct {
	origin      string
	originCtx   string
	originEmail string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectByEmail *mUserMockSelectByEmail) Optional() *mUserMockSelectByEmail {
	mmSelectByEmail.optional = true
	return mmSelectByEmail
}

// Expect sets up expected params for User.SelectByEmail
func (mmSelectByEmail *mUserMockSelectByEmail) Expect(ctx context.Context, email string) *mUserMockSelectByEmail {
	if mmSelectByEmail.mock.funcSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Set")
	}

	if mmSelectByEmail.defaultExpectation == nil {
		mmSelectByEmail.defaultExpectation = &UserMockSelectByEmailExpectation{}
	}

	if mmSelectByEmail.defaultExpectation.paramPtrs != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by ExpectParams functions")
	}

	mmSelectByEmail.defaultExpectation.params = &UserMockSelectByEmailParams{ctx, email}
	mmSelectByEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectByEmail.expectations {
		if minimock.Equal(e.params, mmSelectByEmail.defaultExpectation.params) {
			mmSelectByEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectByEmail.defaultExpectation.params)
		}
	}

	return mmSelectByEmail
}

// ExpectCtxParam1 sets up expected param ctx for User.SelectByEmail
func (mmSelectByEmail *mUserMockSelectByEmail) ExpectCtxParam1(ctx context.Context) *mUserMockSelectByEmail {
	if mmSelectByEmail.mock.funcSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Set")
	}

	if mmSelectByEmail.defaultExpectation == nil {
		mmSelectByEmail.defaultExpectation = &UserMockSelectByEmailExpectation{}
	}

	if mmSelectByEmail.defaultExpectation.params != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Expect")
	}

	if mmSelectByEmail.defaultExpectation.paramPtrs == nil {
		mmSelectByEmail.defaultExpectation.paramPtrs = &UserMockSelectByEmailParamPtrs{}
	}
	mmSelectByEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectByEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectByEmail
}

// ExpectEmailParam2 sets up expected param email for User.SelectByEmail
func (mmSelectByEmail *mUserMockSelectByEmail) ExpectEmailParam2(email string) *mUserMockSelectByEmail {
	if mmSelectByEmail.mock.funcSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Set")
	}

	if mmSelectByEmail.defaultExpectation == nil {
		mmSelectByEmail.defaultExpectation = &UserMockSelectByEmailExpectation{}
	}

	if mmSelectByEmail.defaultExpectation.params != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Expect")
	}

	if mmSelectByEmail.defaultExpectation.paramPtrs == nil {
		mmSelectByEmail.defaultExpectation.paramPtrs = &UserMockSelectByEmailParamPtrs{}
	}
	mmSelectByEmail.defaultExpectation.paramPtrs.email = &email
	mmSelectByEmail.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmSelectByEmail
}

// Inspect accepts an inspector function that has same arguments as the User.SelectByEmail
func (mmSelectByEmail *mUserMockSelectByEmail) Inspect(f func(ctx context.Context, email string)) *mUserMockSelectByEmail {
	if mmSelectByEmail.mock.inspectFuncSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("Inspect function is already set for UserMock.SelectByEmail")
	}

	mmSelectByEmail.mock.inspectFuncSelectByEmail = f

	return mmSelectByEmail
}

// Return sets up results that will be returned by User.SelectByEmail
func (mmSelectByEmail *mUserMockSelectByEmail) Return(ua1 []domain.User, err error) *UserMock {
	if mmSelectByEmail.mock.funcSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Set")
	}

	if mmSelectByEmail.defaultExpectation == nil {
		mmSelectByEmail.defaultExpectation = &UserMockSelectByEmailExpectation{mock: mmSelectByEmail.mock}
	}
	mmSelectByEmail.defaultExpectation.results = &UserMockSelectByEmailResults{ua1, err}
	mmSelectByEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectByEmail.mock
}

// Set uses given function f to mock the User.SelectByEmail method
func (mmSelectByEmail *mUserMockSelectByEmail) Set(f func(ctx context.Context, email string) (ua1 []domain.User, err error)) *UserMock {
	if mmSelectByEmail.defaultExpectation != nil {
		mmSelectByEmail.mock.t.Fatalf("Default expectation is already set for the User.SelectByEmail method")
	}

	if len(mmSelectByEmail.expectations) > 0 {
		mmSelectByEmail.mock.t.Fatalf("Some expectations are already set for the User.SelectByEmail method")
	}

	mmSelectByEmail.mock.funcSelectByEmail = f
	mmSelectByEmail.mock.funcSelectByEmailOrigin = minimock.CallerInfo(1)
	return mmSelectByEmail.mock
}

// When sets expectation for the User.SelectByEmail which will trigger the result defined by the following
// Then helper
func (mmSelectByEmail *mUserMockSelectByEmail) When(ctx context.Context, email string) *UserMockSelectByEmailExpectation {
	if mmSelectByEmail.mock.funcSelectByEmail != nil {
		mmSelectByEmail.mock.t.Fatalf("UserMock.SelectByEmail mock is already set by Set")
	}

	expectation := &UserMockSelectByEmailExpectation{
		mock:               mmSelectByEmail.mock,
		params:             &UserMockSelectByEmailParams{ctx, email},
		expectationOrigins: UserMockSelectByEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectByEmail.expectations = append(mmSelectByEmail.expectations, expectation)
	return expectation
}

// Then sets up User.SelectByEmail return parameters for the expectation previously defined by the When method
func (e *UserMockSelectByEmailExpectation) Then(ua1 []domain.User, err error) *UserMock {
	e.results = &UserMockSelectByEmailResults{ua1, err}
	return e.mock
}

// Times sets number of times User.SelectByEmail should be invoked
func (mmSelectByEmail *mUserMockSelectByEmail) Times(n uint64) *mUserMockSelectByEmail {
	if n == 0 {
		mmSelectByEmail.mock.t.Fatalf("Times of UserMock.SelectByEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectByEmail.expectedInvocations, n)
	mmSelectByEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectByEmail
}

func (mmSelectByEmail *mUserMockSelectByEmail) invocationsDone() bool {
	if len(mmSelectByEmail.expectations) == 0 && mmSelectByEmail.defaultExpectation == nil && mmSelectByEmail.mock.funcSelectByEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectByEmail.mock.afterSelectByEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectByEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectByEmail implements mm_repository.User
func (mmSelectByEmail *UserMock) SelectByEmail(ctx context.Context, email string) (ua1 []domain.User, err error) {
	mm_atomic.AddUint64(&mmSelectByEmail.beforeSelectByEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectByEmail.afterSelectByEmailCounter, 1)

	mmSelectByEmail.t.Helper()

	if mmSelectByEmail.inspectFuncSelectByEmail != nil {
		mmSelectByEmail.inspectFuncSelectByEmail(ctx, email)
	}

	mm_params := UserMockSelectByEmailParams{ctx, email}

	// Record call args
	mmSelectByEmail.SelectByEmailMock.mutex.Lock()
	mmSelectByEmail.SelectByEmailMock.callArgs = append(mmSelectByEmail.SelectByEmailMock.callArgs, &mm_params)
	mmSelectByEmail.SelectByEmailMock.mutex.Unlock()

	for _, e := range mmSelectByEmail.SelectByEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ua1, e.results.err
		}
	}

	if mmSelectByEmail.SelectByEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectByEmail.SelectByEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectByEmail.SelectByEmailMock.defaultExpectation.params
		mm_want_ptrs := mmSelectByEmail.SelectByEmailMock.defaultExpectation.paramPtrs

		mm_got := UserMockSelectByEmailParams{ctx, email}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectByEmail.t.Errorf("UserMock.SelectByEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByEmail.SelectByEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmSelectByEmail.t.Errorf("UserMock.SelectByEmail got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByEmail.SelectByEmailMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectByEmail.t.Errorf("UserMock.SelectByEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectByEmail.SelectByEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectByEmail.SelectByEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectByEmail.t.Fatal("No results are set for the UserMock.SelectByEmail")
		}
		return (*mm_results).ua1, (*mm_results).err
	}
	if mmSelectByEmail.funcSelectByEmail != nil {
		return mmSelectByEmail.funcSelectByEmail(ctx, email)
	}
	mmSelectByEmail.t.Fatalf("Unexpected call to UserMock.SelectByEmail. %v %v", ctx, email)
	return
}

// SelectByEmailAfterCounter returns a count of finished UserMock.SelectByEmail invocations
func (mmSelectByEmail *UserMock) SelectByEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByEmail.afterSelectByEmailCounter)
}

// SelectByEmailBeforeCounter returns a count of UserMock.SelectByEmail invocations
func (mmSelectByEmail *UserMock) SelectByEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByEmail.beforeSelectByEmailCounter)
}

// Calls returns a list of arguments used in each call to UserMock.SelectByEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectByEmail *mUserMockSelectByEmail) Calls() []*UserMockSelectByEmailParams {
	mmSelectByEmail.mutex.RLock()

	argCopy := make([]*UserMockSelectByEmailParams, len(mmSelectByEmail.callArgs))
	copy(argCopy, mmSelectByEmail.callArgs)

	mmSelectByEmail.mutex.RUnlock()

	return argCopy
}

// MinimockSelectByEmailDone returns true if the count of the SelectByEmail invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockSelectByEmailDone() bool {
	if m.SelectByEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectByEmailMock.invocationsDone()
}

// MinimockSelectByEmailInspect logs each unmet expectation
func (m *UserMock) MinimockSelectByEmailInspect() {
	for _, e := range m.SelectByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.SelectByEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectByEmailCounter := mm_atomic.LoadUint64(&m.afterSelectByEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectByEmailMock.defaultExpectation != nil && afterSelectByEmailCounter < 1 {
		if m.SelectByEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.SelectByEmail at\n%s", m.SelectByEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.SelectByEmail at\n%s with params: %#v", m.SelectByEmailMock.defaultExpectation.expectationOrigins.origin, *m.SelectByEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectByEmail != nil && afterSelectByEmailCounter < 1 {
		m.t.Errorf("Expected call to UserMock.SelectByEmail at\n%s", m.funcSelectByEmailOrigin)
	}

	if !m.SelectByEmailMock.invocationsDone() && afterSelectByEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.SelectByEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectByEmailMock.expectedInvocations), m.SelectByEmailMock.expectedInvocationsOrigin, afterSelectByEmailCounter)
	}
}

type mUserMockSelectByID struct {
	optional           bool
	mock               *UserMock
	defaultExpectation *UserMockSelectByIDExpectation
	expectations       []*UserMockSelectByIDExpectation

	callArgs []*UserMockSelectByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserMockSelectByIDExpectation specifies expectation struct of the User.SelectByID
type UserMockSelectByIDExpectation struct {
	mock               *UserMock
	params             *UserMockSelectByIDParams
	paramPtrs          *UserMockSelectByIDParamPtrs
	expectationOrigins UserMockSelectByIDExpectationOrigins
	results            *UserMockSelectByIDResults
	returnOrigin       string
	Counter            uint64
}

// UserMockSelectByIDParams contains parameters of the User.SelectByID
type UserMockSelectByIDParams struct {
	ctx     context.Context
	usersID []uuid.UUID
}

// UserMockSelectByIDParamPtrs contains pointers to parameters of the User.SelectByID
type UserMockSelectByIDParamPtrs struct {
	ctx     *context.Context
	usersID *[]uuid.UUID
}

// UserMockSelectByIDResults contains results of the User.SelectByID
type UserMockSelectByIDResults struct {
	ua1 []domain.User
	err error
}

// UserMockSelectByIDOrigins contains origins of expectations of the User.SelectByID
type UserMockSelectByIDExpectationOrigins struct {
	origin        string
	originCtx     string
	originUsersID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSelectByID *mUserMockSelectByID) Optional() *mUserMockSelectByID {
	mmSelectByID.optional = true
	return mmSelectByID
}

// Expect sets up expected params for User.SelectByID
func (mmSelectByID *mUserMockSelectByID) Expect(ctx context.Context, usersID ...uuid.UUID) *mUserMockSelectByID {
	if mmSelectByID.mock.funcSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Set")
	}

	if mmSelectByID.defaultExpectation == nil {
		mmSelectByID.defaultExpectation = &UserMockSelectByIDExpectation{}
	}

	if mmSelectByID.defaultExpectation.paramPtrs != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by ExpectParams functions")
	}

	mmSelectByID.defaultExpectation.params = &UserMockSelectByIDParams{ctx, usersID}
	mmSelectByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSelectByID.expectations {
		if minimock.Equal(e.params, mmSelectByID.defaultExpectation.params) {
			mmSelectByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSelectByID.defaultExpectation.params)
		}
	}

	return mmSelectByID
}

// ExpectCtxParam1 sets up expected param ctx for User.SelectByID
func (mmSelectByID *mUserMockSelectByID) ExpectCtxParam1(ctx context.Context) *mUserMockSelectByID {
	if mmSelectByID.mock.funcSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Set")
	}

	if mmSelectByID.defaultExpectation == nil {
		mmSelectByID.defaultExpectation = &UserMockSelectByIDExpectation{}
	}

	if mmSelectByID.defaultExpectation.params != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Expect")
	}

	if mmSelectByID.defaultExpectation.paramPtrs == nil {
		mmSelectByID.defaultExpectation.paramPtrs = &UserMockSelectByIDParamPtrs{}
	}
	mmSelectByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmSelectByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSelectByID
}

// ExpectUsersIDParam2 sets up expected param usersID for User.SelectByID
func (mmSelectByID *mUserMockSelectByID) ExpectUsersIDParam2(usersID ...uuid.UUID) *mUserMockSelectByID {
	if mmSelectByID.mock.funcSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Set")
	}

	if mmSelectByID.defaultExpectation == nil {
		mmSelectByID.defaultExpectation = &UserMockSelectByIDExpectation{}
	}

	if mmSelectByID.defaultExpectation.params != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Expect")
	}

	if mmSelectByID.defaultExpectation.paramPtrs == nil {
		mmSelectByID.defaultExpectation.paramPtrs = &UserMockSelectByIDParamPtrs{}
	}
	mmSelectByID.defaultExpectation.paramPtrs.usersID = &usersID
	mmSelectByID.defaultExpectation.expectationOrigins.originUsersID = minimock.CallerInfo(1)

	return mmSelectByID
}

// Inspect accepts an inspector function that has same arguments as the User.SelectByID
func (mmSelectByID *mUserMockSelectByID) Inspect(f func(ctx context.Context, usersID ...uuid.UUID)) *mUserMockSelectByID {
	if mmSelectByID.mock.inspectFuncSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("Inspect function is already set for UserMock.SelectByID")
	}

	mmSelectByID.mock.inspectFuncSelectByID = f

	return mmSelectByID
}

// Return sets up results that will be returned by User.SelectByID
func (mmSelectByID *mUserMockSelectByID) Return(ua1 []domain.User, err error) *UserMock {
	if mmSelectByID.mock.funcSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Set")
	}

	if mmSelectByID.defaultExpectation == nil {
		mmSelectByID.defaultExpectation = &UserMockSelectByIDExpectation{mock: mmSelectByID.mock}
	}
	mmSelectByID.defaultExpectation.results = &UserMockSelectByIDResults{ua1, err}
	mmSelectByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSelectByID.mock
}

// Set uses given function f to mock the User.SelectByID method
func (mmSelectByID *mUserMockSelectByID) Set(f func(ctx context.Context, usersID ...uuid.UUID) (ua1 []domain.User, err error)) *UserMock {
	if mmSelectByID.defaultExpectation != nil {
		mmSelectByID.mock.t.Fatalf("Default expectation is already set for the User.SelectByID method")
	}

	if len(mmSelectByID.expectations) > 0 {
		mmSelectByID.mock.t.Fatalf("Some expectations are already set for the User.SelectByID method")
	}

	mmSelectByID.mock.funcSelectByID = f
	mmSelectByID.mock.funcSelectByIDOrigin = minimock.CallerInfo(1)
	return mmSelectByID.mock
}

// When sets expectation for the User.SelectByID which will trigger the result defined by the following
// Then helper
func (mmSelectByID *mUserMockSelectByID) When(ctx context.Context, usersID ...uuid.UUID) *UserMockSelectByIDExpectation {
	if mmSelectByID.mock.funcSelectByID != nil {
		mmSelectByID.mock.t.Fatalf("UserMock.SelectByID mock is already set by Set")
	}

	expectation := &UserMockSelectByIDExpectation{
		mock:               mmSelectByID.mock,
		params:             &UserMockSelectByIDParams{ctx, usersID},
		expectationOrigins: UserMockSelectByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSelectByID.expectations = append(mmSelectByID.expectations, expectation)
	return expectation
}

// Then sets up User.SelectByID return parameters for the expectation previously defined by the When method
func (e *UserMockSelectByIDExpectation) Then(ua1 []domain.User, err error) *UserMock {
	e.results = &UserMockSelectByIDResults{ua1, err}
	return e.mock
}

// Times sets number of times User.SelectByID should be invoked
func (mmSelectByID *mUserMockSelectByID) Times(n uint64) *mUserMockSelectByID {
	if n == 0 {
		mmSelectByID.mock.t.Fatalf("Times of UserMock.SelectByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSelectByID.expectedInvocations, n)
	mmSelectByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSelectByID
}

func (mmSelectByID *mUserMockSelectByID) invocationsDone() bool {
	if len(mmSelectByID.expectations) == 0 && mmSelectByID.defaultExpectation == nil && mmSelectByID.mock.funcSelectByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSelectByID.mock.afterSelectByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSelectByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SelectByID implements mm_repository.User
func (mmSelectByID *UserMock) SelectByID(ctx context.Context, usersID ...uuid.UUID) (ua1 []domain.User, err error) {
	mm_atomic.AddUint64(&mmSelectByID.beforeSelectByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmSelectByID.afterSelectByIDCounter, 1)

	mmSelectByID.t.Helper()

	if mmSelectByID.inspectFuncSelectByID != nil {
		mmSelectByID.inspectFuncSelectByID(ctx, usersID...)
	}

	mm_params := UserMockSelectByIDParams{ctx, usersID}

	// Record call args
	mmSelectByID.SelectByIDMock.mutex.Lock()
	mmSelectByID.SelectByIDMock.callArgs = append(mmSelectByID.SelectByIDMock.callArgs, &mm_params)
	mmSelectByID.SelectByIDMock.mutex.Unlock()

	for _, e := range mmSelectByID.SelectByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ua1, e.results.err
		}
	}

	if mmSelectByID.SelectByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSelectByID.SelectByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmSelectByID.SelectByIDMock.defaultExpectation.params
		mm_want_ptrs := mmSelectByID.SelectByIDMock.defaultExpectation.paramPtrs

		mm_got := UserMockSelectByIDParams{ctx, usersID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSelectByID.t.Errorf("UserMock.SelectByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByID.SelectByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.usersID != nil && !minimock.Equal(*mm_want_ptrs.usersID, mm_got.usersID) {
				mmSelectByID.t.Errorf("UserMock.SelectByID got unexpected parameter usersID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSelectByID.SelectByIDMock.defaultExpectation.expectationOrigins.originUsersID, *mm_want_ptrs.usersID, mm_got.usersID, minimock.Diff(*mm_want_ptrs.usersID, mm_got.usersID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSelectByID.t.Errorf("UserMock.SelectByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSelectByID.SelectByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSelectByID.SelectByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmSelectByID.t.Fatal("No results are set for the UserMock.SelectByID")
		}
		return (*mm_results).ua1, (*mm_results).err
	}
	if mmSelectByID.funcSelectByID != nil {
		return mmSelectByID.funcSelectByID(ctx, usersID...)
	}
	mmSelectByID.t.Fatalf("Unexpected call to UserMock.SelectByID. %v %v", ctx, usersID)
	return
}

// SelectByIDAfterCounter returns a count of finished UserMock.SelectByID invocations
func (mmSelectByID *UserMock) SelectByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByID.afterSelectByIDCounter)
}

// SelectByIDBeforeCounter returns a count of UserMock.SelectByID invocations
func (mmSelectByID *UserMock) SelectByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSelectByID.beforeSelectByIDCounter)
}

// Calls returns a list of arguments used in each call to UserMock.SelectByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSelectByID *mUserMockSelectByID) Calls() []*UserMockSelectByIDParams {
	mmSelectByID.mutex.RLock()

	argCopy := make([]*UserMockSelectByIDParams, len(mmSelectByID.callArgs))
	copy(argCopy, mmSelectByID.callArgs)

	mmSelectByID.mutex.RUnlock()

	return argCopy
}

// MinimockSelectByIDDone returns true if the count of the SelectByID invocations corresponds
// the number of defined expectations
func (m *UserMock) MinimockSelectByIDDone() bool {
	if m.SelectByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SelectByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SelectByIDMock.invocationsDone()
}

// MinimockSelectByIDInspect logs each unmet expectation
func (m *UserMock) MinimockSelectByIDInspect() {
	for _, e := range m.SelectByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserMock.SelectByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSelectByIDCounter := mm_atomic.LoadUint64(&m.afterSelectByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SelectByIDMock.defaultExpectation != nil && afterSelectByIDCounter < 1 {
		if m.SelectByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserMock.SelectByID at\n%s", m.SelectByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserMock.SelectByID at\n%s with params: %#v", m.SelectByIDMock.defaultExpectation.expectationOrigins.origin, *m.SelectByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSelectByID != nil && afterSelectByIDCounter < 1 {
		m.t.Errorf("Expected call to UserMock.SelectByID at\n%s", m.funcSelectByIDOrigin)
	}

	if !m.SelectByIDMock.invocationsDone() && afterSelectByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UserMock.SelectByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SelectByIDMock.expectedInvocations), m.SelectByIDMock.expectedInvocationsOrigin, afterSelectByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockInsertInspect()

			m.MinimockSelectByEmailInspect()

			m.MinimockSelectByIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockInsertDone() &&
		m.MinimockSelectByEmailDone() &&
		m.MinimockSelectByIDDone()
}
